In [1]:
from google.colab import files 
uploaded = files.upload() 


Saving data.csv to data.csv


In [2]:
import io 
import pandas as pd
data = pd.read_csv(io.BytesIO(uploaded['data.csv'])) 
print(type(data))
print(data.head())

<class 'pandas.core.frame.DataFrame'>
                                                URLs  ... Label
0  http://www.bbc.com/news/world-us-canada-414191...  ...     1
1  https://www.reuters.com/article/us-filmfestiva...  ...     1
2  https://www.nytimes.com/2017/10/09/us/politics...  ...     1
3  https://www.reuters.com/article/us-mexico-oil-...  ...     1
4  http://www.cnn.com/videos/cnnmoney/2017/10/08/...  ...     1

[5 rows x 4 columns]


In [3]:
url_data=data.dropna()
url_data.head()

URLs  ... Label
0  http://www.bbc.com/news/world-us-canada-414191...  ...     1
1  https://www.reuters.com/article/us-filmfestiva...  ...     1
2  https://www.nytimes.com/2017/10/09/us/politics...  ...     1
3  https://www.reuters.com/article/us-mexico-oil-...  ...     1
4  http://www.cnn.com/videos/cnnmoney/2017/10/08/...  ...     1

[5 rows x 4 columns]

In [4]:
url_data.shape

(3988, 4)

In [5]:
data_x=url_data.iloc[:,:-1]
data_x.head()

URLs  ...                                               Body
0  http://www.bbc.com/news/world-us-canada-414191...  ...  Image copyright Getty Images\nOn Sunday mornin...
1  https://www.reuters.com/article/us-filmfestiva...  ...  LONDON (Reuters) - “Last Flag Flying”, a comed...
2  https://www.nytimes.com/2017/10/09/us/politics...  ...  The feud broke into public view last week when...
3  https://www.reuters.com/article/us-mexico-oil-...  ...  MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...
4  http://www.cnn.com/videos/cnnmoney/2017/10/08/...  ...  Country singer Jason Aldean, who was performin...

[5 rows x 3 columns]

In [6]:
data_y=url_data.iloc[:,3:]
data_y.head()

Label
0      1
1      1
2      1
3      1
4      1

In [7]:
print(data_x.shape)
print(data_y.shape)

(3988, 3)
(3988, 1)


In [0]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
#from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from matplotlib import pyplot as plt
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier

In [0]:
def split_data(x,y):
    
    """
    Reminder : Clean the set before sending here.
    Input  : x=Attributes of the dataset, y=Target Attribute
    Output : Split data of train test
    
    We are removing dev , as dev can be better used for the models that includes DNN, CNN and RNN
    
    """
    X=x
    Y=y
    
    train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.2,random_state=12)
    
    #train_x : Training data with attributes
    #train_y : Training data with ratings
    #test_x  : testing data with attributes
    #test_y  : testing data with rating 
    
    print("Final size of train/test :",train_x.size,"/",test_x.size)
    return train_x,train_y,test_x,test_y

In [10]:
import numpy as np
a=np.array([])
a.size

0

In [0]:
def passive_aggressive(train_x,train_y,test_x,test_y,stop=False):
    
    if stop==True:
        print("Early Stopping is being used")
    
    pac= PassiveAggressiveClassifier(early_stopping=stop)
    pac.fit(train_x, train_y)
    predicted_pac_train=pac.predict(train_x)
    predicted_pac_test= pac.predict(test_x)
    
    score_train= metrics.accuracy_score(train_y, predicted_pac_train)
    score_test=metrics.accuracy_score(test_y,predicted_pac_test)
    
    print("train accuracy:",score_train)
    cm_pac_train= metrics.confusion_matrix(train_y, predicted_pac_train)
    print("train confusion matrix")
    print(cm_pac_train)
    print("test accuracy:",score_test)
    cm_pac_test= metrics.confusion_matrix(test_y, predicted_pac_test)
    print("test confusion matrix")
    print(cm_pac_test)

In [0]:
def mult_tfidf_pac(x1,y,stop=False):
    from sklearn.feature_extraction.text import TfidfVectorizer

    #if x3.size==0:
    train_x1,train_y1,test_x1,test_y1=split_data(x1,y)
        #train_x2,train_y2,test_x2,test_y2=split_data(x2,y)



    tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
    tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
    tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        #tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        #tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 

        #train=pd.concat([tfidf_train_x1,tfidf_train_x2],axis=1)
        #test=pd.concat([tfidf_test_x1,tfidf_test_x2],axis=1)
    print(tfidf_train_x1.shape)
    print(tfidf_test_x1.shape)
    #    print(train_y2.shape)
     #   print(test_y2.shape)

    passive_aggressive(tfidf_train_x1,train_y1,tfidf_test_x1,test_y1)
    
    '''else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3],axis=1)
        
        passive_aggressive(train,train_y2,test,test_y2)'''

In [13]:
mult_tfidf_pac(x1=data_x.URLs,y=data_y.Label,stop=True)

Final size of train/test : 3190 / 798
(3190, 46)
(798, 46)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 1.0
test confusion matrix
[[432   0]
 [  0 366]]


In [14]:
mult_tfidf_pac(x1=data_x.Headline,y=data_y.Label,stop=True)

Final size of train/test : 3190 / 798
(3190, 14)
(798, 14)
train accuracy: 0.5529780564263322
train confusion matrix
[[1577  111]
 [1315  187]]
test accuracy: 0.5614035087719298
test confusion matrix
[[405  27]
 [323  43]]


In [15]:
mult_tfidf_pac(x1=data_x.Body,y=data_y.Label,stop=True)

Final size of train/test : 3190 / 798
(3190, 1945)
(798, 1945)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9824561403508771
test confusion matrix
[[419  13]
 [  1 365]]


In [16]:
mult_tfidf_pac(x1=data_x.URLs,y=data_y.Label,stop=False)

Final size of train/test : 3190 / 798
(3190, 46)
(798, 46)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 1.0
test confusion matrix
[[432   0]
 [  0 366]]


In [18]:
mult_tfidf_pac(x1=data_x.Headline,y=data_y.Label,stop=False)

Final size of train/test : 3190 / 798
(3190, 14)
(798, 14)
train accuracy: 0.5551724137931034
train confusion matrix
[[1509  179]
 [1240  262]]
test accuracy: 0.5476190476190477
test confusion matrix
[[387  45]
 [316  50]]


In [19]:
mult_tfidf_pac(x1=data_x.Body,y=data_y.Label,stop=False)

Final size of train/test : 3190 / 798
(3190, 1945)
(798, 1945)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.981203007518797
test confusion matrix
[[419  13]
 [  2 364]]


In [0]:
#tfidf_pac start 
" " " mult_tfidf_pac(x1=data_x.URLs,x2=data_x.Headline,y=data_y.Label,x3=data_x.Body,stop=True) #early stopping true
Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
Early Stopping is being used
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9987468671679198
test confusion matrix
[[432   0]
 [  1 365]]

In [0]:
" " " mult_tfidf_pac(x1=data_x.URLs,x2=data_x.Headline,y=data_y.Label,x3=data_x.Body) #early stopping false
Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9987468671679198
test confusion matrix
[[432   0]
 [  1 365]]

In [0]:
mult_tfidf_pac(x1=data_x.URLs,x2=data_x.Headline,y=data_y.Label,x3=a,stop=True) #early stopping true

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 60)
(798, 60)
(3190,)
(798,)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 1.0
test confusion matrix
[[432   0]
 [  0 366]]


In [0]:
mult_tfidf_pac(x1=data_x.URLs,x2=data_x.Headline,y=data_y.Label,x3=a)#early stopping false

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 60)
(798, 60)
(3190,)
(798,)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9987468671679198
test confusion matrix
[[432   0]
 [  1 365]]


In [0]:
mult_tfidf_pac(x1=data_x.URLs,x2=data_x.Body,y=data_y.Label,x3=a,stop=True) #early stopping true

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 1991)
(798, 1991)
(3190,)
(798,)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 1.0
test confusion matrix
[[432   0]
 [  0 366]]


In [0]:
mult_tfidf_pac(x1=data_x.URLs,x2=data_x.Headline,y=data_y.Label,x3=a)#early stoping false

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 60)
(798, 60)
(3190,)
(798,)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9987468671679198
test confusion matrix
[[432   0]
 [  1 365]]


In [0]:
mult_tfidf_pac(x1=data_x.URLs,x2=data_x.Body,y=data_y.Label,x3=a) #early stopping false

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 1991)
(798, 1991)
(3190,)
(798,)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 1.0
test confusion matrix
[[432   0]
 [  0 366]]


In [0]:
mult_tfidf_pac(x1=data_x.Body,x2=data_x.Headline,y=data_y.Label,x3=a,stop=True) #early stopping true

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 1959)
(798, 1959)
(3190,)
(798,)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9849624060150376
test confusion matrix
[[423   9]
 [  3 363]]


In [0]:
mult_tfidf_pac(x1=data_x.Body,x2=data_x.Headline,y=data_y.Label,x3=a)

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 1959)
(798, 1959)
(3190,)
(798,)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9799498746867168
test confusion matrix
[[419  13]
 [  3 363]]


In [0]:
#hashv start 
def multi_hashv_pac(x1,x2,y,x3=a,stop=False):
    from sklearn.feature_extraction.text import HashingVectorizer
    # Not sure about this, collisions may occur as I forced absolute cause naivie bayes is a bitch and n_features over 
                                                                                        #2**15 causes memory error
    
    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=split_data(x2,y)



        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**8)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()))  #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()))  #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense())) 

        train=pd.concat([hash_train_x1,hash_train_x2],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        passive_aggressive(train,train_y2,test,test_y2,stop)
    
    else:
        train_x1,train_y1,test_x1,test_y1=split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=split_data(x3,y)
        
        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**8)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()) ) #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()) ) #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense()) )
        
        hash_train_x3 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x3).todense()))  #fitting the training data
        hash_test_x3 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x3).todense()))
        
        train=pd.concat([hash_train_x1,hash_train_x2,hash_train_x3],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2,hash_test_x3],axis=1)
        
        passive_aggressiv(train,train_y2,test,test_y2,stop)

In [0]:
" " " multi_hashv_pac(x1=data_x.URLs,x2=data_x.Headline,y=data_y.Label,x3=data_x.Body) #early stopping false
Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9974937343358395
test confusion matrix
[[431   1]
 [  1 365]]

In [0]:
" " " multi_hashv_pac(x1=data_x.URLs,x2=data_x.Headline,y=data_y.Label,x3=data_x.Body,stop=True) #early stopping true
Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
Early Stopping is being used
train accuracy: 0.9993730407523511
train confusion matrix
[[1686    2]
 [   0 1502]]
test accuracy: 0.9962406015037594
test confusion matrix
[[430   2]
 [  1 365]]

In [0]:
multi_hashv_pac(x1=data_x.URLs,x2=data_x.Headline,y=data_y.Label,x3=a,stop=True) #early stopping true

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 512)
(798, 512)
(3190,)
(798,)
Early Stopping is being used
train accuracy: 0.9987460815047022
train confusion matrix
[[1685    3]
 [   1 1501]]
test accuracy: 0.993734335839599
test confusion matrix
[[428   4]
 [  1 365]]


In [0]:
multi_hashv_pac(x1=data_x.URLs,x2=data_x.Headline,y=data_y.Label,x3=a)

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 512)
(798, 512)
(3190,)
(798,)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9949874686716792
test confusion matrix
[[429   3]
 [  1 365]]


In [0]:
multi_hashv_pac(x1=data_x.URLs,x2=data_x.Body,y=data_y.Label,x3=a,stop=True)

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 512)
(798, 512)
(3190,)
(798,)
Early Stopping is being used
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9987468671679198
test confusion matrix
[[432   0]
 [  1 365]]


In [0]:
multi_hashv_pac(x1=data_x.URLs,x2=data_x.Body,y=data_y.Label,x3=a)

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 512)
(798, 512)
(3190,)
(798,)
train accuracy: 1.0
train confusion matrix
[[1688    0]
 [   0 1502]]
test accuracy: 0.9987468671679198
test confusion matrix
[[432   0]
 [  1 365]]


In [0]:
multi_hashv_pac(x1=data_x.Body,x2=data_x.Headline,y=data_y.Label,x3=a,stop=True)

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 512)
(798, 512)
(3190,)
(798,)
Early Stopping is being used
train accuracy: 0.9197492163009404
train confusion matrix
[[1447  241]
 [  15 1487]]
test accuracy: 0.8596491228070176
test confusion matrix
[[342  90]
 [ 22 344]]


In [0]:
multi_hashv_pac(x1=data_x.Body,x2=data_x.Headline,y=data_y.Label,x3=a)

Final size of train/test : 3190 / 798
Final size of train/test : 3190 / 798
(3190, 512)
(798, 512)
(3190,)
(798,)
train accuracy: 0.9689655172413794
train confusion matrix
[[1602   86]
 [  13 1489]]
test accuracy: 0.8922305764411027
test confusion matrix
[[385  47]
 [ 39 327]]
