In [3]:
import numpy as np
import import_ipynb
#import auto_naive as an
import auto_pac as ap
import pandas as pd

#import dtale as d

In [4]:
data=pd.read_csv('liar_data.csv')
#data1=d.show(data)
data.columns

Index(['label', 'statement', 'subject', 'speaker', 'speaker_job_title',
       'state_info', 'party', 'context'],
      dtype='object')

In [ ]:
#tfidf model building both early stoping and hashing

In [6]:
ap.pac_tfidf_model(data.statement,data.label)

Final size of train/test : 6750 / 1688
train accuracy: 0.9976296296296296
train confusion matrix
[[4990    4]
 [  12 1744]]
test accuracy: 0.625
test confusion matrix
[[905 312]
 [321 150]]


In [8]:
ap.pac_tfidf_model(data.statement,data.label,stop=True)

Final size of train/test : 6750 / 1688
Early Stopping is being used
train accuracy: 0.9241481481481482
train confusion matrix
[[4790  204]
 [ 308 1448]]
test accuracy: 0.6404028436018957
test confusion matrix
[[951 266]
 [341 130]]


In [39]:
ap.pac_tfidf_model(data.subject,data.label)

Final size of train/test : 6750 / 1688
train accuracy: 0.7051851851851851
train confusion matrix
[[4610  384]
 [1606  150]]
test accuracy: 0.6919431279620853
test confusion matrix
[[1132   85]
 [ 435   36]]


In [50]:
ap.pac_tfidf_model(data.subject,data.label,stop=True)

Final size of train/test : 6750 / 1688
Early Stopping is being used
train accuracy: 0.6826666666666666
train confusion matrix
[[4327  667]
 [1475  281]]
test accuracy: 0.6646919431279621
test confusion matrix
[[1058  159]
 [ 407   64]]


In [51]:
ap.pac_tfidf_model(data.speaker,data.label)

Final size of train/test : 6750 / 1688
train accuracy: 0.7579259259259259
train confusion matrix
[[4488  506]
 [1128  628]]
test accuracy: 0.6575829383886256
test confusion matrix
[[1027  190]
 [ 388   83]]


In [52]:
ap.pac_tfidf_model(data.speaker,data.label,stop=True)

Final size of train/test : 6750 / 1688
Early Stopping is being used
train accuracy: 0.7494814814814815
train confusion matrix
[[4586  408]
 [1283  473]]
test accuracy: 0.6670616113744076
test confusion matrix
[[1075  142]
 [ 420   51]]


In [53]:
ap.pac_tfidf_model(data.speaker_job_title,data.label)

Final size of train/test : 6750 / 1688
train accuracy: 0.7007407407407408
train confusion matrix
[[4294  700]
 [1320  436]]
test accuracy: 0.6481042654028436
test confusion matrix
[[1017  200]
 [ 394   77]]


In [65]:
ap.pac_tfidf_model(data.speaker_job_title,data.label,stop=True)

Final size of train/test : 6750 / 1688
Early Stopping is being used
train accuracy: 0.6619259259259259
train confusion matrix
[[3866 1128]
 [1154  602]]
test accuracy: 0.601303317535545
test confusion matrix
[[900 317]
 [356 115]]


In [66]:
ap.pac_tfidf_model(data.state_info,data.label)

Final size of train/test : 6750 / 1688
train accuracy: 0.6385185185185185
train confusion matrix
[[3830 1164]
 [1276  480]]
test accuracy: 0.615521327014218
test confusion matrix
[[928 289]
 [360 111]]


In [67]:
ap.pac_tfidf_model(data.state_info,data.label,stop=True)

Final size of train/test : 6750 / 1688
Early Stopping is being used
train accuracy: 0.7031111111111111
train confusion matrix
[[4595  399]
 [1605  151]]
test accuracy: 0.6800947867298578
test confusion matrix
[[1109  108]
 [ 432   39]]


In [68]:
ap.pac_tfidf_model(data.party,data.label)

Final size of train/test : 6750 / 1688
train accuracy: 0.7402962962962963
train confusion matrix
[[4990    4]
 [1749    7]]
test accuracy: 0.7186018957345972
test confusion matrix
[[1213    4]
 [ 471    0]]


In [69]:
ap.pac_tfidf_model(data.party,data.label,stop=True)

Final size of train/test : 6750 / 1688
Early Stopping is being used
train accuracy: 0.7398518518518519
train confusion matrix
[[4993    1]
 [1755    1]]
test accuracy: 0.7209715639810427
test confusion matrix
[[1217    0]
 [ 471    0]]


In [70]:
ap.pac_tfidf_model(data.context,data.label)

Final size of train/test : 6750 / 1688
train accuracy: 0.7601481481481481
train confusion matrix
[[4604  390]
 [1229  527]]
test accuracy: 0.6558056872037915
test confusion matrix
[[1051  166]
 [ 415   56]]


In [71]:
ap.pac_tfidf_model(data.context,data.label,stop=True)

Final size of train/test : 6750 / 1688
Early Stopping is being used
train accuracy: 0.7469629629629629
train confusion matrix
[[4568  426]
 [1282  474]]
test accuracy: 0.659952606635071
test confusion matrix
[[1052  165]
 [ 409   62]]


In [86]:
#hashing model 
#ap.pac_hash_model(data.statement,data.label)
#we ignoring the hashing models 

In [85]:
#ap.pac_hash_model(data.subject,data.label)

In [84]:
#ap.pac_hash_model(data.speaker,data.label)

In [83]:
#ap.pac_hash_model(data.speaker_job_title,data.label)

In [82]:
#ap.pac_hash_model(data.state_info,data.label)

In [81]:
#ap.pac_hash_model(data.subject,data.label)

In [80]:
#ap.pac_hash_model(data.subject,data.label)

In [77]:
#pac model with all attributes
def mult_tfidf_pac(x1,x2,x3,x4,x5,x6,x7,y,stop=False):
    from sklearn.feature_extraction.text import TfidfVectorizer
    train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
    train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
    train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
    train_x4,train_y4,test_x4,test_y4=an.split_data(x5,y)
    train_x5,train_y5,test_x5,test_y5=an.split_data(x5,y)
    train_x6,train_y6,test_x6,test_y6=an.split_data(x6,y)
    train_x7,train_y7,test_x7,test_y7=an.split_data(x7,y)
    
    tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorize
    
    tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
    tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

    tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
    tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
    tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
    tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
    tfidf_train_x4 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x4).todense())  #fitting the training data
    tfidf_test_x4 = pd.DataFrame(tfidf_vectorizer.transform(test_x4).todense())

    tfidf_train_x5 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x5).todense())  #fitting the training data
    tfidf_test_x5 = pd.DataFrame(tfidf_vectorizer.transform(test_x5).todense()) 
        
    tfidf_train_x6 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x6).todense())  #fitting the training data
    tfidf_test_x6 = pd.DataFrame(tfidf_vectorizer.transform(test_x6).todense())
    
    tfidf_train_x7 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x7).todense())  #fitting the training data
    tfidf_test_x7 = pd.DataFrame(tfidf_vectorizer.transform(test_x7).todense())
        
    train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3,tfidf_train_x4,tfidf_train_x5,tfidf_train_x6,tfidf_train_x7],axis=1)
    test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3,tfidf_test_x4,tfidf_test_x5,tfidf_test_x6,tfidf_test_x7],axis=1)
        
    ap.passive_aggressive(train,train_y7,test,test_y7,stop)


In [78]:
#multiple attribute
mult_tfidf_pac(data.statement,data.subject,data.speaker,data.speaker_job_title,data.state_info,data.party,data.context,data.label)

Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
train accuracy: 0.9997037037037036
train confusion matrix
[[4993    1]
 [   1 1755]]
test accuracy: 0.643957345971564
test confusion matrix
[[946 271]
 [330 141]]


In [79]:
mult_tfidf_pac(data.statement,data.subject,data.speaker,data.speaker_job_title,data.state_info,data.party,data.context,data.label,stop=True)

Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Early Stopping is being used
train accuracy: 0.8663703703703703
train confusion matrix
[[4602  392]
 [ 510 1246]]
test accuracy: 0.6475118483412322
test confusion matrix
[[954 263]
 [332 139]]
