In [1]:
"""
TODO - Clean and run naive bayes and pac
         2 models, 1 with URL and other without URL
         REQUIRES A LOT OF COMMENTING AND DOCUMENTATION
"""

'\nTODO - Clean and run naive bayes and pac\n         2 models, 1 with URL and other without URL\n         REQUIRES A LOT OF COMMENTING AND DOCUMENTATION\n'

In [2]:
import pandas as pd
import numpy as np
import import_ipynb
import auto_naive as an
import auto_pac as ap

importing Jupyter notebook from auto_naive.ipynb
importing Jupyter notebook from auto_pac.ipynb


In [3]:
#Reading this for extraction of URL
pol_data = pd.read_csv('datasets/politifact_data/full_politifact_data.csv',sep='\t',error_bad_lines=False,index_col=False)

b'Skipping line 4022: expected 6 fields, saw 7\nSkipping line 6316: expected 6 fields, saw 7\nSkipping line 9381: expected 6 fields, saw 7\n'


In [4]:
pol_data.head()
#Politifact explanations are not required
pol_data.shape

(10464, 5)

In [5]:
pol_data.URL.to_csv('datasets/politifact_data/pol_data.URL',header=True)

In [6]:
#cleaning and extracting most important part of url
re_url=pd.read_csv('datasets/politifact_data/pol_data.URL',names=['id','url'])

url_only=re_url.url
e_url=[0]*url_only.size

for i in range(url_only.size):
    e_url[i]=url_only[i].split("/")

clean_url=[0]*url_only.size

for i in range(url_only.size):
    clean_url[i]=e_url[i][len(e_url[i])-2]

del clean_url[0]
    


In [7]:
pol_data.columns

Index(['Speaker', 'Truth-Rating', 'Statement', 'PolitiFact explanations',
       'URL'],
      dtype='object')

In [8]:
#dropping old url and updating with clean
pol_data.drop(['URL'], axis=1,inplace=True)
print(pol_data.columns)

Index(['Speaker', 'Truth-Rating', 'Statement', 'PolitiFact explanations'], dtype='object')


In [9]:
print(pol_data.shape)
print(len(clean_url))

(10464, 4)
10464


In [10]:
pol_data.insert(loc=2, column='url', value=clean_url)

In [11]:
pol_data.drop(['PolitiFact explanations'],axis=1,inplace=True)

In [12]:
pol_data.columns
print(pol_data.head(5))

              Speaker  Truth-Rating  \
0         Paul LePage             5   
1  Battleground Texas             0   
2  Battleground Texas             1   
3      Suzanne Somers             0   
4        Jamie Oliver             2   

                                                 url  \
0  maine-gov-paul-lepage-says-47-percent-able-bod...   
1  dan-patrick-has-called-illegal-immigration-inv...   
2  battleground-texas-says-54-percent-texas-latin...   
3  suzanne-somers-says-even-obamacare-tens-millio...   
4        chef-jamie-oliver-praises-mcdonalds-england   

                                           Statement  
0  About 47 percent of able-bodied people in the ...  
1  Says Dan Patrick has "called immigration into ...  
2  In 2008, "only 54 percent of Latinos in Texas ...  
3  Even after Obamacare is fully implemented, the...  
4  McDonald's in England only sells organic milk ...  


In [13]:
#splitting target attribute from the rest

type(pol_data)
pol_data.rename(columns={"Truth-Rating": "label"},inplace=True)
print(pol_data.shape)

(10464, 4)


In [14]:
pol_data_y=pol_data.label
pol_data_x=pol_data.drop(['label'],axis=1)
print(pol_data_x.shape)
print(pol_data_y.shape)

print(pol_data_y.head(5))

(10464, 3)
(10464,)
0    5
1    0
2    1
3    0
4    2
Name: label, dtype: int64


In [15]:
#Former Ratings [ 0:True 1:Mostly True 2:Half True 3:Half false 4:Mostly false 5:False]
#Actual Ratings [0,1,2 = 1 and 3,4,5 = 0]\

pol_data_y.replace({0:"True",1:"True",2:"True",3:"False",4:"False",5:"False"},inplace=True)

pol_data_y.head(5)

0    False
1     True
2     True
3     True
4     True
Name: label, dtype: object

In [16]:
pol_data_x.columns
"""
Naive Bayes Models : 

"""

'\nNaive Bayes Models : \n\n'

In [17]:
an.navie_bayes_tfidf_model(pol_data_x.Statement,pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
train_x : (8371,)
train_y : (8371,)
test_x : (2093,)
test_y : (2093,)
Vectorizing
test_x : (2093,)
train_x : (8371,)
tfidf_train_x :  (8371, 10646)
tfidf_test_x :  (2093, 10646)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.6093656671843268
grid alpha 0.463
Alpha: 0.463 test_Score: 0.60153 train_score: 0.82834
training confusion matrix
[[2428 1214]
 [ 223 4506]]
testing confusion matrix
[[290 609]
 [225 969]]
------------------------------------------


In [18]:
an.navie_bayes_tfidf_model(pol_data_x.Speaker,pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
train_x : (8371,)
train_y : (8371,)
test_x : (2093,)
test_y : (2093,)
Vectorizing
test_x : (2093,)
train_x : (8371,)
tfidf_train_x :  (8371, 2879)
tfidf_test_x :  (2093, 2879)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.5951499223509736
grid alpha 0.985
Alpha: 0.985 test_Score: 0.60248 train_score: 0.72369
training confusion matrix
[[1999 1643]
 [ 670 4059]]
testing confusion matrix
[[316 583]
 [249 945]]
------------------------------------------


In [19]:
an.navie_bayes_tfidf_model(pol_data_x.url,pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
train_x : (8371,)
train_y : (8371,)
test_x : (2093,)
test_y : (2093,)
Vectorizing
test_x : (2093,)
train_x : (8371,)
tfidf_train_x :  (8371, 9785)
tfidf_test_x :  (2093, 9785)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.6038705053159719
grid alpha 0.732
Alpha: 0.732 test_Score: 0.61921 train_score: 0.84339
training confusion matrix
[[2557 1085]
 [ 226 4503]]
testing confusion matrix
[[318 581]
 [216 978]]
------------------------------------------


In [20]:
an.navie_bayes_hash_model(pol_data_x.Statement,pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.6014813045036436
grid alpha 0.011
Alpha: 0.011 test_Score: 0.59866 train_score: 0.84207
training confusion matrix
[[2411 1231]
 [  91 4638]]
testing confusion matrix
[[277 622]
 [218 976]]
------------------------------------------


In [21]:
an.navie_bayes_hash_model(pol_data_x.url,pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.5956277625134393
grid alpha 0.14
Alpha: 0.140 test_Score: 0.60057 train_score: 0.80456
training confusion matrix
[[2057 1585]
 [  51 4678]]
testing confusion matrix
[[ 191  708]
 [ 128 1066]]
------------------------------------------


In [22]:
an.navie_bayes_hash_model(pol_data_x.Speaker,pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.5988531836100824
grid alpha 0.426
Alpha: 0.426 test_Score: 0.61108 train_score: 0.71258
training confusion matrix
[[1681 1961]
 [ 445 4284]]
testing confusion matrix
[[ 266  633]
 [ 181 1013]]
------------------------------------------


In [17]:
def mult_tfidf(x1,x2,y,x3=a):
    from sklearn.feature_extraction.text import TfidfVectorizer

    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 

        train=pd.concat([tfidf_train_x1,tfidf_train_x2],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        an.navie_bayes(train,train_y2,test,test_y2)
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3],axis=1)
        
        an.navie_bayes(train,train_y2,test,test_y2)

        

In [60]:

mult_tfidf(pol_data_x.url,pol_data_x.Speaker,pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 12664)
(2093, 12664)
(8371,)
(2093,)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.6100824274280253
grid alpha 0.999
Alpha: 0.999 test_Score: 0.63641 train_score: 0.81747
training confusion matrix
[[2554 1088]
 [ 440 4289]]
testing confusion matrix
[[363 536]
 [225 969]]
------------------------------------------


In [64]:
mult_tfidf(x1=pol_data_x.url,x2=pol_data_x.Statement,y=pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 20431)
(2093, 20431)
(8371,)
(2093,)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.620953291124119
grid alpha 0.9530000000000001
Alpha: 0.953 test_Score: 0.62828 train_score: 0.86262
training confusion matrix
[[2639 1003]
 [ 147 4582]]
testing confusion matrix
[[ 313  586]
 [ 192 1002]]
------------------------------------------


In [28]:
mult_tfidf(x1=pol_data_x.Statement,x2=pol_data_x.Speaker,y=pol_data_y,x3=a)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 13525)
(2093, 13525)
(8371,)
(2093,)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.6208338310835025
grid alpha 0.997
Alpha: 0.997 test_Score: 0.64071 train_score: 0.81125
training confusion matrix
[[2415 1227]
 [ 353 4376]]
testing confusion matrix
[[ 335  564]
 [ 188 1006]]
------------------------------------------


In [77]:
mult_tfidf(x1=pol_data_x.Statement,x2=pol_data_x.Speaker,y=pol_data_y,x3=pol_data_x.url)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.6287181937641859
grid alpha 0.9460000000000001
Alpha: 0.946 test_Score: 0.63832 train_score: 0.85533
training confusion matrix
[[2706  936]
 [ 275 4454]]
testing confusion matrix
[[354 545]
 [212 982]]
------------------------------------------


In [19]:
a=np.array([])
a.size

0

In [41]:
def multi_hashv(x1,x2,y,x3=a):
    from sklearn.feature_extraction.text import HashingVectorizer
    # Not sure about this, collisions may occur as I forced absolute cause naivie bayes is a bitch and n_features over 
                                                                                        #2**15 causes memory error
    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**15)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()))  #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()))  #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense())) 

        train=pd.concat([hash_train_x1,hash_train_x2],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        an.navie_bayes(train,train_y2,test,test_y2,100)
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**15)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()) ) #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()) ) #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense()) )
        
        hash_train_x3 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x3).todense()))  #fitting the training data
        hash_test_x3 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x3).todense()))
        
        train=pd.concat([hash_train_x1,hash_train_x2,hash_train_x3],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2,hash_test_x3],axis=1)
        
        an.navie_bayes(train,train_y2,test,test_y2,100)


0

In [20]:
multi_hashv(x1=pol_data_x.Statement,x2=pol_data_x.Speaker,y=pol_data_y,x3=a)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 65536)
(2093, 65536)
(8371,)
(2093,)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.6214311312865847
grid alpha 0.27
Alpha: 0.270 test_Score: 0.62828 train_score: 0.80528
training confusion matrix
[[2268 1374]
 [ 256 4473]]
testing confusion matrix
[[ 298  601]
 [ 177 1017]]
------------------------------------------


In [21]:
multi_hashv(x1=pol_data_x.Statement,x2=pol_data_x.url,y=pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 65536)
(2093, 65536)
(8371,)
(2093,)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.6184446302711742
grid alpha 0.18000000000000002
Alpha: 0.180 test_Score: 0.61586 train_score: 0.87469
training confusion matrix
[[2719  923]
 [ 126 4603]]
testing confusion matrix
[[327 572]
 [232 962]]
------------------------------------------


In [22]:
multi_hashv(x1=pol_data_x.url,x2=pol_data_x.Speaker,y=pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 65536)
(2093, 65536)
(8371,)
(2093,)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.610560267590491
grid alpha 0.92
Alpha: 0.920 test_Score: 0.63067 train_score: 0.75367
training confusion matrix
[[1823 1819]
 [ 243 4486]]
testing confusion matrix
[[ 249  650]
 [ 123 1071]]
------------------------------------------


In [42]:
multi_hashv(x1=pol_data_x.url,x2=pol_data_x.Speaker,y=pol_data_y,x3=pol_data_x.Statement)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.6302711742921993
grid alpha 0.2
Alpha: 0.200 test_Score: 0.63163 train_score: 0.86501
training confusion matrix
[[2706  936]
 [ 194 4535]]
testing confusion matrix
[[344 555]
 [216 978]]
------------------------------------------


In [23]:
"""

-------------------------------------------------------------------------

"""

'\n\n-------------------------------------------------------------------------\n\n'

In [ ]:
"""
Start building pac models 

"""


In [19]:
ap.pac_tfidf_model(pol_data_x.Statement,pol_data_y) #too much overfitting

Final size of train/test : 8371 / 2093
train accuracy: 0.9941464580097957
train confusion matrix
[[3608   34]
 [  15 4714]]
test accuracy: 0.5456282847587195
test confusion matrix
[[423 476]
 [475 719]]


In [20]:
ap.pac_tfidf_model(pol_data_x.url,pol_data_y) 

Final size of train/test : 8371 / 2093
train accuracy: 0.9948632182534942
train confusion matrix
[[3618   24]
 [  19 4710]]
test accuracy: 0.5733397037744864
test confusion matrix
[[434 465]
 [428 766]]


In [21]:
ap.pac_tfidf_model(pol_data_x.Speaker,pol_data_y) 

Final size of train/test : 8371 / 2093
train accuracy: 0.7185521443077291
train confusion matrix
[[2083 1559]
 [ 797 3932]]
test accuracy: 0.590539894887721
test confusion matrix
[[341 558]
 [299 895]]


In [22]:
ap.pac_tfidf_model(pol_data_x.Statement,pol_data_y,stop=True)

Final size of train/test : 8371 / 2093
Early Stopping is being used
train accuracy: 0.9053876478318003
train confusion matrix
[[3179  463]
 [ 329 4400]]
test accuracy: 0.5661729574773053
test confusion matrix
[[394 505]
 [403 791]]


In [24]:
ap.pac_tfidf_model(pol_data_x.url,pol_data_y,stop=True) 

Final size of train/test : 8371 / 2093
Early Stopping is being used
train accuracy: 0.9115995699438538
train confusion matrix
[[3214  428]
 [ 312 4417]]
test accuracy: 0.5895843287147635
test confusion matrix
[[406 493]
 [366 828]]


In [23]:
ap.pac_tfidf_model(pol_data_x.Speaker,pol_data_y,stop=True) 

Final size of train/test : 8371 / 2093
Early Stopping is being used
train accuracy: 0.6653924262334249
train confusion matrix
[[2661  981]
 [1820 2909]]
test accuracy: 0.5437171524128046
test confusion matrix
[[477 422]
 [533 661]]


In [17]:
a=np.array([])
a.size

0

In [29]:
def mult_tfidf_pac(x1,x2,y,x3=a,stop=False):
    from sklearn.feature_extraction.text import TfidfVectorizer

    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 

        train=pd.concat([tfidf_train_x1,tfidf_train_x2],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        ap.passive_aggressive(train,train_y2,test,test_y2,stop)
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3],axis=1)
        
        ap.passive_aggressive(train,train_y2,test,test_y2,stop)

        

In [30]:
mult_tfidf_pac(x1=pol_data_x.Statement,x2=pol_data_x.Speaker,y=pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 13525)
(2093, 13525)
(8371,)
(2093,)
train accuracy: 0.9990443196750687
train confusion matrix
[[3641    1]
 [   7 4722]]
test accuracy: 0.5714285714285714
test confusion matrix
[[502 397]
 [500 694]]


In [32]:
mult_tfidf_pac(x1=pol_data_x.Statement,x2=pol_data_x.url,y=pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 20431)
(2093, 20431)
(8371,)
(2093,)
train accuracy: 1.0
train confusion matrix
[[3642    0]
 [   0 4729]]
test accuracy: 0.5938843764930721
test confusion matrix
[[440 459]
 [391 803]]


In [33]:
mult_tfidf_pac(x1=pol_data_x.url,x2=pol_data_x.Speaker,y=pol_data_y)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 12664)
(2093, 12664)
(8371,)
(2093,)
train accuracy: 0.9962967387408912
train confusion matrix
[[3635    7]
 [  24 4705]]
test accuracy: 0.5771619684663163
test confusion matrix
[[488 411]
 [474 720]]


In [34]:
mult_tfidf_pac(x1=pol_data_x.Statement,x2=pol_data_x.Speaker,y=pol_data_y,x3=pol_data_x.url)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
train accuracy: 1.0
train confusion matrix
[[3642    0]
 [   0 4729]]
test accuracy: 0.6139512661251791
test confusion matrix
[[441 458]
 [350 844]]


In [38]:
mult_tfidf_pac(x1=pol_data_x.Statement,x2=pol_data_x.Speaker,y=pol_data_y,stop=True)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 13525)
(2093, 13525)
(8371,)
(2093,)
Early Stopping is being used
train accuracy: 0.8141201768008601
train confusion matrix
[[3487  155]
 [1401 3328]]
test accuracy: 0.5441949354992833
test confusion matrix
[[598 301]
 [653 541]]


In [37]:
mult_tfidf_pac(x1=pol_data_x.Statement,x2=pol_data_x.url,y=pol_data_y,stop=True)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 20431)
(2093, 20431)
(8371,)
(2093,)
Early Stopping is being used
train accuracy: 0.9534105841595986
train confusion matrix
[[3430  212]
 [ 178 4551]]
test accuracy: 0.5972288580984233
test confusion matrix
[[432 467]
 [376 818]]


In [36]:
mult_tfidf_pac(x1=pol_data_x.url,x2=pol_data_x.Speaker,y=pol_data_y,stop=True)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 12664)
(2093, 12664)
(8371,)
(2093,)
Early Stopping is being used
train accuracy: 0.887707561820571
train confusion matrix
[[3362  280]
 [ 660 4069]]
test accuracy: 0.592451027233636
test confusion matrix
[[517 382]
 [471 723]]


In [35]:
mult_tfidf_pac(x1=pol_data_x.Statement,x2=pol_data_x.Speaker,y=pol_data_y,x3=pol_data_x.url,stop=True)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
Early Stopping is being used
train accuracy: 0.9505435431848047
train confusion matrix
[[3482  160]
 [ 254 4475]]
test accuracy: 0.6077400860009555
test confusion matrix
[[522 377]
 [444 750]]


In [ ]:
#pac hash now 

In [19]:
ap.pac_hash_model(pol_data_x.Statement,pol_data_y)

Final size of train/test : 8371 / 2093
train accuracy: 0.984111814598017
train confusion matrix
[[3560   82]
 [  51 4678]]
test accuracy: 0.5470616340181558
test confusion matrix
[[430 469]
 [479 715]]


In [20]:
ap.pac_hash_model(pol_data_x.url,pol_data_y)

Final size of train/test : 8371 / 2093
train accuracy: 0.9886512961414406
train confusion matrix
[[3568   74]
 [  21 4708]]
test accuracy: 0.5733397037744864
test confusion matrix
[[397 502]
 [391 803]]


In [21]:
ap.pac_hash_model(pol_data_x.Speaker,pol_data_y)

Final size of train/test : 8371 / 2093
train accuracy: 0.7103094015051965
train confusion matrix
[[2413 1229]
 [1196 3533]]
test accuracy: 0.5747730530339226
test confusion matrix
[[415 484]
 [406 788]]


In [22]:
ap.pac_hash_model(pol_data_x.Statement,pol_data_y,stop=True)

Final size of train/test : 8371 / 2093
Early Stopping is being used
train accuracy: 0.8535419902042767
train confusion matrix
[[2772  870]
 [ 356 4373]]
test accuracy: 0.5628284758719542
test confusion matrix
[[349 550]
 [365 829]]


In [23]:
ap.pac_hash_model(pol_data_x.url,pol_data_y,stop=True)

Final size of train/test : 8371 / 2093
Early Stopping is being used
train accuracy: 0.882809700155298
train confusion matrix
[[3057  585]
 [ 396 4333]]
test accuracy: 0.5910176779741997
test confusion matrix
[[415 484]
 [372 822]]


In [24]:
ap.pac_hash_model(pol_data_x.Speaker,pol_data_y,stop=True)

Final size of train/test : 8371 / 2093
Early Stopping is being used
train accuracy: 0.6997969179309521
train confusion matrix
[[1875 1767]
 [ 746 3983]]
test accuracy: 0.5943621595795509
test confusion matrix
[[311 588]
 [261 933]]


In [37]:
def multi_hashv_pac(x1,x2,y,x3=a,stop=False):
    from sklearn.feature_extraction.text import HashingVectorizer
    # Not sure about this, collisions may occur as I forced absolute cause naivie bayes is a bitch and n_features over 
                                                                                        #2**15 causes memory error
    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**15)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()))  #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()))  #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense())) 

        train=pd.concat([hash_train_x1,hash_train_x2],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        ap.passive_aggressive(train,train_y2,test,test_y2,stop)    
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**15)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()) ) #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()) ) #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense()) )
        
        hash_train_x3 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x3).todense()))  #fitting the training data
        hash_test_x3 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x3).todense()))
        
        train=pd.concat([hash_train_x1,hash_train_x2,hash_train_x3],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2,hash_test_x3],axis=1)
        
        ap.passive_aggressive(train,train_y2,test,test_y2,stop)


In [26]:
multi_hashv_pac(x1=pol_data_x.Statement,x2=pol_data_x.Speaker,y=pol_data_y,x3=a,stop=False)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 65536)
(2093, 65536)
(8371,)
(2093,)
train accuracy: 0.9960578186596584
train confusion matrix
[[3616   26]
 [   7 4722]]
test accuracy: 0.5805064500716675
test confusion matrix
[[424 475]
 [403 791]]


In [27]:
multi_hashv_pac(x1=pol_data_x.Statement,x2=pol_data_x.Speaker,y=pol_data_y,x3=a,stop=True)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 65536)
(2093, 65536)
(8371,)
(2093,)
Early Stopping is being used
train accuracy: 0.8430295066300323
train confusion matrix
[[2995  647]
 [ 667 4062]]
test accuracy: 0.5891065456282848
test confusion matrix
[[437 462]
 [398 796]]


In [28]:
multi_hashv_pac(x1=pol_data_x.Statement,x2=pol_data_x.url,y=pol_data_y,x3=a,stop=False)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 65536)
(2093, 65536)
(8371,)
(2093,)
train accuracy: 1.0
train confusion matrix
[[3642    0]
 [   0 4729]]
test accuracy: 0.5871954132823698
test confusion matrix
[[444 455]
 [409 785]]


In [29]:
multi_hashv_pac(x1=pol_data_x.url,x2=pol_data_x.Speaker,y=pol_data_y,x3=a,stop=False)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 65536)
(2093, 65536)
(8371,)
(2093,)
train accuracy: 0.9934296977660972
train confusion matrix
[[3605   37]
 [  18 4711]]
test accuracy: 0.5876731963688485
test confusion matrix
[[413 486]
 [377 817]]


In [30]:
multi_hashv_pac(x1=pol_data_x.Statement,x2=pol_data_x.url,y=pol_data_y,x3=a,stop=True)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 65536)
(2093, 65536)
(8371,)
(2093,)
Early Stopping is being used
train accuracy: 0.9157806713654283
train confusion matrix
[[3287  355]
 [ 350 4379]]
test accuracy: 0.5852842809364549
test confusion matrix
[[436 463]
 [405 789]]


In [31]:
multi_hashv_pac(x1=pol_data_x.url,x2=pol_data_x.Speaker,y=pol_data_y,x3=a,stop=True)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
(8371, 65536)
(2093, 65536)
(8371,)
(2093,)
Early Stopping is being used
train accuracy: 0.8280970015529805
train confusion matrix
[[3152  490]
 [ 949 3780]]
test accuracy: 0.5814620162446249
test confusion matrix
[[492 407]
 [469 725]]


In [38]:
multi_hashv_pac(x1=pol_data_x.url,x2=pol_data_x.Speaker,y=pol_data_y,stop=True,x3=pol_data_x.Statement)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
Early Stopping is being used
train accuracy: 0.8659658344283837
train confusion matrix
[[3489  153]
 [ 969 3760]]
test accuracy: 0.5661729574773053
test confusion matrix
[[601 298]
 [610 584]]


In [39]:
multi_hashv_pac(x1=pol_data_x.url,x2=pol_data_x.Speaker,y=pol_data_y,stop=False,x3=pol_data_x.Statement)

Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
Splitting
Final size of train/test : 8371 / 2093
train accuracy: 1.0
train confusion matrix
[[3642    0]
 [   0 4729]]
test accuracy: 0.6005733397037745
test confusion matrix
[[441 458]
 [378 816]]
