In [1]:
import pandas as pd
import numpy as np
import import_ipynb
import auto_naive as an
import auto_pac as ap

importing Jupyter notebook from auto_naive.ipynb
importing Jupyter notebook from auto_pac.ipynb


In [2]:
dataset=pd.read_csv('datasets/pontes set/resized_v2.csv')

C:\Users\Rahul\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (1,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
dataset.columns

Index(['Unnamed: 0', 'id', 'domain', 'type', 'url', 'content', 'scraped_at',
       'inserted_at', 'updated_at', 'title', 'authors', 'keywords',
       'meta_keywords', 'meta_description', 'tags', 'summary', 'source'],
      dtype='object')

In [4]:
dataset.type.unique()

array(['clickbait', 'satire', 'unreliable', 'hate', 'reliable',
       'conspiracy', 'fake', 'political', 'bias', 'rumor', 'junksci', nan,
       'unknown', '2018-02-10 13:43:39.521661'], dtype=object)

In [5]:
dataset.shape

(426550, 17)

In [6]:
"""
So much columns 
So many rows
So many types 
;-;

"""

'\nSo much columns \nSo many rows\nSo many types \n;-;\n\n'

In [7]:
dataset.iloc[:,0:2]

#here the first column i,e unnamed and id will be dropped as they are not required

Unnamed: 0       id
0                0       21
1                1       22
2                2       54
3                3       61
4                4       64
...            ...      ...
426545      426545  9878188
426546      426546  9878196
426547      426547  9878220
426548      426548  9878237
426549      426549  9878253

[426550 rows x 2 columns]

In [8]:
dataset.drop(['id', 'Unnamed: 0'], axis=1,inplace=True)

In [9]:
print(dataset.columns)
print(dataset.shape)

Index(['domain', 'type', 'url', 'content', 'scraped_at', 'inserted_at',
       'updated_at', 'title', 'authors', 'keywords', 'meta_keywords',
       'meta_description', 'tags', 'summary', 'source'],
      dtype='object')
(426550, 15)


In [10]:
dataset.source

#domain is the website with which it was accessed
#type is the label
#url is not required as the domain covers the website which we got in 
#content is very important
#all 3 at dates are not important
#title is required
#authors too
#all keywords are NaN, an guessing this gets updated after applying nlp
#meta keywords are just weird, missing and weird
#meta description has NAn but unsure how useful this is
#Removing tags due to too many missing values
#summary all NAN
#how is source different from domain
#remove extra columns

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
           ...   
426545    nytimes
426546    nytimes
426547    nytimes
426548    nytimes
426549    nytimes
Name: source, Length: 426550, dtype: object

In [11]:
dataset.isna().sum()/(len(dataset))*100
#shows percentage of nulls
#source gets dropped due to too much null


domain                0.001172
type                  4.723948
url                   0.001172
content               0.001172
scraped_at            0.001407
inserted_at           0.001407
updated_at            0.001407
title                 0.853827
authors              44.418708
keywords            100.000000
meta_keywords         4.017583
meta_description     52.563357
tags                 76.969640
summary             100.000000
source               77.875982
dtype: float64

In [12]:
dataset.drop(['url', 'scraped_at', 'inserted_at', 'updated_at','keywords', 'meta_keywords',
       'meta_description', 'tags', 'summary'], axis=1,inplace=True)

In [13]:
dataset.drop(['source'], axis=1,inplace=True)

In [14]:
dataset.isna().sum()/(len(dataset))*100


domain      0.001172
type        4.723948
content     0.001172
title       0.853827
authors    44.418708
dtype: float64

In [15]:
dataset.rename(columns={"type": "label"},inplace=True)

In [16]:
"""
2 new routes will be established now

Route 1: Remove authors and continue
Route 2: Since authors are important, we can remove all rows whose authors value is nan

"""

'\n2 new routes will be established now\n\nRoute 1: Remove authors and continue\nRoute 2: Since authors are important, we can remove all rows whose authors value is nan\n\n'

In [17]:
"""

Taking route 1 now :)
drop authors

"""

'\n\nTaking route 1 now :)\ndrop authors\n\n'

In [18]:
r1=dataset.drop(['authors'], axis=1)

In [19]:
r1.columns

Index(['domain', 'label', 'content', 'title'], dtype='object')

In [20]:
r1.shape

(426550, 4)

In [21]:
r1.label.unique()
#click baits are false
#satire can be true or false
#hate unknown
#reliable is true
#conspiracy can be true, or wait is it a conspiracy that all conspiracies are false?
#fake is fake 
#political and everything else are ignored

array(['clickbait', 'satire', 'unreliable', 'hate', 'reliable',
       'conspiracy', 'fake', 'political', 'bias', 'rumor', 'junksci', nan,
       'unknown', '2018-02-10 13:43:39.521661'], dtype=object)

In [22]:
c_r1=r1[r1.label == 'clickbait']

In [23]:
d_r1=r1[r1.label == 'reliable']

In [24]:
e_r1=r1[r1.label == 'fake']

In [25]:
print(c_r1.size,d_r1.size,e_r1.size)

46288 384096 177840


In [26]:
r1_clean=pd.concat([c_r1,d_r1,e_r1])

In [27]:
r1_clean.replace({'clickbait':'fake'},inplace=True)

In [28]:
r1_clean.label.unique()

array(['fake', 'reliable'], dtype=object)

In [29]:
r1_clean.shape
r1_clean.to_csv('datasets/pontes set/route1.csv',index=False)

In [30]:
"""
rerun from here

"""


'\nrerun from here\n\n'

In [31]:
route1=pd.read_csv('datasets/pontes set/route1.csv')

In [32]:
print(route1.shape)
print(route1.columns)
print(route1.head(6))
print(route1.label.unique())



(152056, 4)
Index(['domain', 'label', 'content', 'title'], dtype='object')
                 domain label  \
0  bipartisanreport.com  fake   
1  bipartisanreport.com  fake   
2  bipartisanreport.com  fake   
3       breaking911.com  fake   
4  bipartisanreport.com  fake   
5  bipartisanreport.com  fake   

                                             content  \
0  The website from which you got to this page is...   
1  When the news broke that Stephanie Clifford, a...   
2  President Trump’s year or so in office has bee...   
3  Baltimore — David Thornton was found guilty by...   
4  The federal government remained shut down goin...   
5  Special Counsel Robert S. Mueller is doing any...   

                                               title  
0                                   Email Protection  
1  ‘Wall St Journal’ Rocks Trump With Friday Shad...  
2  John Kelly Is On His Way Out And Ivanka Trump ...  
3  Murderer on Parole Receives Maximum Sentence A...  
4  NY Times Reveals Why T

In [33]:
route1.dropna(subset=["title"], inplace=True)
route1.shape
route1_y=route1.label
route1_x=route1.drop(['label'],axis=1)

In [34]:
print(route1_y.shape)
print(route1_x.shape)
print(route1_x.columns)


(152055,)
(152055, 3)
Index(['domain', 'content', 'title'], dtype='object')


In [35]:
"""
build models for route 1 naive bayes
Fake :224128
Truth:384096 
"""

'\nbuild models for route 1 naive bayes\nFake :224128\nTruth:384096 \n'

In [36]:
route1.isna().sum()/(len(route1))*100


domain     0.0
label      0.0
content    0.0
title      0.0
dtype: float64

In [37]:
route1.isna().sum()


domain     0
label      0
content    0
title      0
dtype: int64

In [38]:
an.navie_bayes_tfidf_model(route1_x.domain,route1_y,100)

Splitting
Final size of train/test : 121644 / 30411
train_x : (121644,)
train_y : (121644,)
test_x : (30411,)
test_y : (30411,)
Vectorizing
test_x : (30411,)
train_x : (121644,)
tfidf_train_x :  (121644, 176)
tfidf_test_x :  (30411, 176)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 1.0
grid alpha 0.001
Alpha: 0.001 test_Score: 0.99997 train_score: 1.00000
training confusion matrix
[[44965     0]
 [    0 76679]]
testing confusion matrix
[[11065     1]
 [    0 19345]]
------------------------------------------


In [53]:
an.navie_bayes_tfidf_model(route1_x.content,route1_y,100)

Splitting
Final size of train/test : 121644 / 30411
train_x : (121644,)
train_y : (121644,)
test_x : (30411,)
test_y : (30411,)
Vectorizing
test_x : (30411,)
train_x : (121644,)
tfidf_train_x :  (121644, 378240)
tfidf_test_x :  (30411, 378240)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9030120680017099
grid alpha 0.006
Alpha: 0.006 test_Score: 0.90773 train_score: 0.95508
training confusion matrix
[[32090  3528]
 [ 1936 84090]]
testing confusion matrix
[[ 6868  1973]
 [  833 20737]]
------------------------------------------


In [54]:
an.navie_bayes_tfidf_model(route1_x.title,route1_y,100)

Splitting
Final size of train/test : 121644 / 30411
train_x : (121644,)
train_y : (121644,)
test_x : (30411,)
test_y : (30411,)
Vectorizing
test_x : (30411,)
train_x : (121644,)
tfidf_train_x :  (121644, 61767)
tfidf_test_x :  (30411, 61767)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7973677287823485
grid alpha 0.17200000000000001
Alpha: 0.172 test_Score: 0.80057 train_score: 0.87703
training confusion matrix
[[22769 12849]
 [ 2109 83917]]
testing confusion matrix
[[ 3997  4844]
 [ 1221 20349]]
------------------------------------------


In [55]:
an.navie_bayes_hash_model(route1_x.domain,route1_y,100)

Splitting
Final size of train/test : 121644 / 30411
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9998602479366019
grid alpha 0.001
Alpha: 0.001 test_Score: 1.00000 train_score: 1.00000
training confusion matrix
[[35618     0]
 [    0 86026]]
testing confusion matrix
[[ 8841     0]
 [    0 21570]]
------------------------------------------


In [56]:
an.navie_bayes_hash_model(route1_x.content,route1_y,100)

Splitting
Final size of train/test : 121644 / 30411
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9092598073065667
grid alpha 0.001
Alpha: 0.001 test_Score: 0.91230 train_score: 0.94406
training confusion matrix
[[31231  4387]
 [ 2418 83608]]
testing confusion matrix
[[ 7063  1778]
 [  889 20681]]
------------------------------------------


In [57]:
an.navie_bayes_hash_model(route1_x.title,route1_y,100)

Splitting
Final size of train/test : 121644 / 30411
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7927065864325409
grid alpha 0.006
Alpha: 0.006 test_Score: 0.79882 train_score: 0.88309
training confusion matrix
[[23627 11991]
 [ 2231 83795]]
testing confusion matrix
[[ 4284  4557]
 [ 1561 20009]]
------------------------------------------


In [40]:
a=np.array([])
a.size

0

In [41]:
def mult_tfidf(x1,x2,y,x3=a,itera=100):
    from sklearn.feature_extraction.text import TfidfVectorizer

    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 

        train=pd.concat([tfidf_train_x1,tfidf_train_x2],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        an.navie_bayes(train,train_y2,test,test_y2,itera)
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3],axis=1)
        
        an.navie_bayes(train,train_y2,test,test_y2,itera)

        

In [42]:
mult_tfidf(x1=route1_x.domain,x2=route1_x.content,x3=route1_x.title,y=route1_y)

Splitting
Final size of train/test : 121644 / 30411
Splitting
Final size of train/test : 121644 / 30411
Splitting
Final size of train/test : 121644 / 30411
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9653743711157147
grid alpha 0.79
Alpha: 0.790 test_Score: 0.96613 train_score: 0.96566
training confusion matrix
[[42409  2556]
 [ 1621 75058]]
testing confusion matrix
[[10423   643]
 [  387 18958]]
------------------------------------------


In [43]:
mult_tfidf(x1=route1_x.domain,x2=route1_x.content,y=route1_y)

Splitting
Final size of train/test : 121644 / 30411
Splitting
Final size of train/test : 121644 / 30411
(121644, 1730)
(30411, 1730)
(121644,)
(30411,)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9649551149255203
grid alpha 0.44
Alpha: 0.440 test_Score: 0.96557 train_score: 0.96521
training confusion matrix
[[42149  2816]
 [ 1416 75263]]
testing confusion matrix
[[10358   708]
 [  339 19006]]
------------------------------------------


In [ ]:
"""
hash has been ignored because of memory errors
unto to pac

"""

In [49]:
ap.pac_tfidf_model(route1_x.domain,route1_y)

Final size of train/test : 121644 / 30411
train accuracy: 1.0
train confusion matrix
[[44965     0]
 [    0 76679]]
test accuracy: 1.0
test confusion matrix
[[11066     0]
 [    0 19345]]


In [48]:
ap.pac_tfidf_model(route1_x.content,route1_y)

Final size of train/test : 121644 / 30411
train accuracy: 0.9999588964519417
train confusion matrix
[[44962     3]
 [    2 76677]]
test accuracy: 0.9441320574792016
test confusion matrix
[[10229   837]
 [  862 18483]]


In [47]:
ap.pac_tfidf_model(route1_x.title,route1_y,True)

Final size of train/test : 121644 / 30411
Early Stopping is being used
train accuracy: 0.904837065535497
train confusion matrix
[[38107  6858]
 [ 4718 71961]]
test accuracy: 0.7895827167801125
test confusion matrix
[[ 7433  3633]
 [ 2766 16579]]


In [50]:
ap.pac_tfidf_model(route1_x.title,route1_y,True)

Final size of train/test : 121644 / 30411
Early Stopping is being used
train accuracy: 0.9043356022491862
train confusion matrix
[[38393  6572]
 [ 5065 71614]]
test accuracy: 0.7884975831113742
test confusion matrix
[[ 7539  3527]
 [ 2905 16440]]


In [51]:
ap.pac_tfidf_model(route1_x.domain,route1_y,True)

Final size of train/test : 121644 / 30411
Early Stopping is being used
train accuracy: 1.0
train confusion matrix
[[44965     0]
 [    0 76679]]
test accuracy: 1.0
test confusion matrix
[[11066     0]
 [    0 19345]]


In [52]:
ap.pac_tfidf_model(route1_x.content,route1_y,True)

Final size of train/test : 121644 / 30411
Early Stopping is being used
train accuracy: 0.9935303015356286
train confusion matrix
[[44588   377]
 [  410 76269]]
test accuracy: 0.9464338561704646
test confusion matrix
[[10242   824]
 [  805 18540]]


In [55]:
def mult_tfidf_pac(x1,x2,y,x3=a,stop=False):
    from sklearn.feature_extraction.text import TfidfVectorizer

    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 

        train=pd.concat([tfidf_train_x1,tfidf_train_x2],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        ap.passive_aggressive(train,train_y2,test,test_y2,stop)
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3],axis=1)
        
        ap.passive_aggressive(train,train_y2,test,test_y2,stop)

        

In [56]:
mult_tfidf_pac(x1=route1_x.domain,x2=route1_x.content,x3=route1_x.title,y=route1_y)

Splitting
Final size of train/test : 121644 / 30411
Splitting
Final size of train/test : 121644 / 30411
Splitting
Final size of train/test : 121644 / 30411
train accuracy: 0.9892801946664036
train confusion matrix
[[44723   242]
 [ 1062 75617]]
test accuracy: 0.9845121830916445
test confusion matrix
[[10947   119]
 [  352 18993]]


In [57]:
mult_tfidf_pac(x1=route1_x.domain,x2=route1_x.content,x3=route1_x.title,y=route1_y,stop=True)

Splitting
Final size of train/test : 121644 / 30411
Splitting
Final size of train/test : 121644 / 30411
Splitting
Final size of train/test : 121644 / 30411
Early Stopping is being used
train accuracy: 0.9900447206602874
train confusion matrix
[[44368   597]
 [  614 76065]]
test accuracy: 0.9850054256683437
test confusion matrix
[[10842   224]
 [  232 19113]]


In [58]:
mult_tfidf_pac(x1=route1_x.domain,x2=route1_x.content,y=route1_y)

Splitting
Final size of train/test : 121644 / 30411
Splitting
Final size of train/test : 121644 / 30411
(121644, 1730)
(30411, 1730)
(121644,)
(30411,)
train accuracy: 0.977401269277564
train confusion matrix
[[42372  2593]
 [  156 76523]]
test accuracy: 0.973627963565815
test confusion matrix
[[10348   718]
 [   84 19261]]


In [59]:
mult_tfidf_pac(x1=route1_x.domain,x2=route1_x.content,y=route1_y,stop=True)

Splitting
Final size of train/test : 121644 / 30411
Splitting
Final size of train/test : 121644 / 30411
(121644, 1730)
(30411, 1730)
(121644,)
(30411,)
Early Stopping is being used
train accuracy: 0.9892555325375686
train confusion matrix
[[44726   239]
 [ 1068 75611]]
test accuracy: 0.9850054256683437
test confusion matrix
[[10959   107]
 [  349 18996]]
