In [4]:
import pandas as pd
import numpy as np
import import_ipynb
import auto_naive as an
import auto_pac as ap

importing Jupyter notebook from auto_naive.ipynb
importing Jupyter notebook from auto_pac.ipynb


In [2]:
dataset=pd.read_csv('datasets/pontes set/resized_v2.csv')

C:\Users\Rahul\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (1,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
dataset.shape

(426550, 17)

In [4]:
dataset.drop(['id', 'Unnamed: 0'], axis=1,inplace=True)

In [5]:
dataset.columns

Index(['domain', 'type', 'url', 'content', 'scraped_at', 'inserted_at',
       'updated_at', 'title', 'authors', 'keywords', 'meta_keywords',
       'meta_description', 'tags', 'summary', 'source'],
      dtype='object')

In [6]:
dataset.isna().sum()/(len(dataset))*100


domain                0.001172
type                  4.723948
url                   0.001172
content               0.001172
scraped_at            0.001407
inserted_at           0.001407
updated_at            0.001407
title                 0.853827
authors              44.418708
keywords            100.000000
meta_keywords         4.017583
meta_description     52.563357
tags                 76.969640
summary             100.000000
source               77.875982
dtype: float64

In [7]:
dataset.drop(['url', 'scraped_at', 'inserted_at', 'updated_at','keywords', 'meta_keywords',
       'meta_description', 'tags', 'summary'], axis=1,inplace=True)

In [8]:
dataset.isna().sum()/(len(dataset))*100


domain      0.001172
type        4.723948
content     0.001172
title       0.853827
authors    44.418708
source     77.875982
dtype: float64

In [14]:
dataset.drop(['source'],inplace=True,axis=1)

In [16]:
dataset.isna().sum()/(len(dataset))*100


domain      0.001172
type        4.723948
content     0.001172
title       0.853827
authors    44.418708
dtype: float64

In [18]:
print(dataset.shape)
print(dataset.size)
print(dataset.domain.size)

(426550, 5)
2132750
426550


In [23]:
dataset.dropna(inplace=True)

In [24]:
print(dataset.shape)
print(dataset.size)
print(dataset.domain.size)

(224847, 5)
1124235
224847


In [25]:
dataset.isna().sum()/(len(dataset))*100


domain     0.0
type       0.0
content    0.0
title      0.0
authors    0.0
dtype: float64

In [28]:
dataset.type.unique()

array(['satire', 'unreliable', 'hate', 'clickbait', 'conspiracy', 'fake',
       'political', 'bias', 'rumor', 'reliable', 'junksci', 'unknown'],
      dtype=object)

In [44]:
r2=dataset

In [45]:
d_1=r2[r2.type == 'fake']
d_2=r2[r2.type == 'clickbait']
d_3=r2[r2.type == 'reliable']


In [46]:
print(d_1.size,d_2.size,d_3.size)

135040 31125 298925


In [47]:
r2_clean=pd.concat([d_1,d_2,d_3])

In [48]:
r2_clean.shape

(93018, 5)

In [ ]:
r2_clean.to_csv('datasets/pontes set/route2.csv',index=False)

In [ ]:
"""
RErun from here for route 2
"""


In [5]:
route2=pd.read_csv('datasets/pontes set/route2.csv')

In [6]:
print(route2.shape)
print(route2.columns)

(93018, 5)
Index(['domain', 'type', 'content', 'title', 'authors'], dtype='object')


In [7]:
route2.replace({'clickbait':'fake'},inplace=True)

In [8]:
route2.type.unique()


array(['fake', 'reliable'], dtype=object)

In [9]:
route2.rename(columns={"type": "label"},inplace=True)

In [10]:
route2_y=route2.label
route2_x=route2.drop(['label'],axis=1)

In [11]:
print(route2_x.shape)
print(route2_y.shape)
print(route2.columns)

(93018, 4)
(93018,)
Index(['domain', 'label', 'content', 'title', 'authors'], dtype='object')


In [12]:
"""
Building models for Route 2 Naive Bayes


"""

'\nBuilding models for Route 2 Naive Bayes\n\n\n'

In [70]:
an.navie_bayes_tfidf_model(route2_x.domain,route2_y,100)

Splitting
Final size of train/test : 74414 / 18604
train_x : (74414,)
train_y : (74414,)
test_x : (18604,)
test_y : (18604,)
Vectorizing
test_x : (18604,)
train_x : (74414,)
tfidf_train_x :  (74414, 116)
tfidf_test_x :  (18604, 116)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 1.0
grid alpha 0.001
Alpha: 0.001 test_Score: 1.00000 train_score: 1.00000
training confusion matrix
[[26483     0]
 [    0 47931]]
testing confusion matrix
[[ 6750     0]
 [    0 11854]]
------------------------------------------


In [73]:
an.navie_bayes_tfidf_model(route2_x.title,route2_y,100)

Splitting
Final size of train/test : 74414 / 18604
train_x : (74414,)
train_y : (74414,)
test_x : (18604,)
test_y : (18604,)
Vectorizing
test_x : (18604,)
train_x : (74414,)
tfidf_train_x :  (74414, 45409)
tfidf_test_x :  (18604, 45409)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7869083774558551
grid alpha 0.171
Alpha: 0.171 test_Score: 0.79193 train_score: 0.89138
training confusion matrix
[[20028  6455]
 [ 1628 46303]]
testing confusion matrix
[[ 3870  2880]
 [  991 10863]]
------------------------------------------


In [74]:
an.navie_bayes_tfidf_model(route2_x.authors,route2_y,100)

Splitting
Final size of train/test : 74414 / 18604
train_x : (74414,)
train_y : (74414,)
test_x : (18604,)
test_y : (18604,)
Vectorizing
test_x : (18604,)
train_x : (74414,)
tfidf_train_x :  (74414, 13813)
tfidf_test_x :  (18604, 13813)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.963904641599699
grid alpha 0.628
Alpha: 0.628 test_Score: 0.96764 train_score: 0.97703
training confusion matrix
[[25216  1267]
 [  442 47489]]
testing confusion matrix
[[ 6308   442]
 [  160 11694]]
------------------------------------------


In [75]:
an.navie_bayes_tfidf_model(route2_x.content,route2_y,100)

Splitting
Final size of train/test : 74414 / 18604
train_x : (74414,)
train_y : (74414,)
test_x : (18604,)
test_y : (18604,)
Vectorizing
test_x : (18604,)
train_x : (74414,)
tfidf_train_x :  (74414, 305793)
tfidf_test_x :  (18604, 305793)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9240196737173113
grid alpha 0.012
Alpha: 0.012 test_Score: 0.92131 train_score: 0.96924
training confusion matrix
[[25004  1479]
 [  810 47121]]
testing confusion matrix
[[ 5715  1035]
 [  429 11425]]
------------------------------------------


In [13]:
a=np.array([])
a.size

0

In [86]:
def mult_tfidf(x1,x2,y,x3=a,itera=100):
    from sklearn.feature_extraction.text import TfidfVectorizer

    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 

        train=pd.concat([tfidf_train_x1,tfidf_train_x2],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        an.navie_bayes(train,train_y2,test,test_y2,itera)
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3],axis=1)
        
        an.navie_bayes(train,train_y2,test,test_y2,itera)

        

In [83]:
mult_tfidf(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9690112075684683
grid alpha 0.9
Alpha: 0.900 test_Score: 0.97054 train_score: 0.96944
training confusion matrix
[[24741  1742]
 [  532 47399]]
testing confusion matrix
[[ 6325   425]
 [  123 11731]]
------------------------------------------


In [25]:
def mult_tfidf4(x1,x2,y,x3,x4,itera=100):
        from sklearn.feature_extraction.text import TfidfVectorizer

        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        train_x4,train_y4,test_x4,test_y4=an.split_data(x3,y)

        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        tfidf_train_x4 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x4).todense())  #fitting the training data
        tfidf_test_x4 = pd.DataFrame(tfidf_vectorizer.transform(test_x4).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3,tfidf_train_x4],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3,tfidf_test_x4],axis=1)
        
        an.navie_bayes(train,train_y2,test,test_y2,itera)

In [92]:
mult_tfidf4(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y,x4=route2_x.title)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9681914693471658
grid alpha 0.13
Alpha: 0.130 test_Score: 0.96968 train_score: 0.96859
training confusion matrix
[[24715  1768]
 [  569 47362]]
testing confusion matrix
[[ 6315   435]
 [  129 11725]]
------------------------------------------


In [ ]:
#nb hash model

In [19]:
an.navie_bayes_hash_model(route2_x.domain,route2_y,100)

Splitting
Final size of train/test : 74414 / 18604
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9999328083425162
grid alpha 0.001
Alpha: 0.001 test_Score: 1.00000 train_score: 1.00000
training confusion matrix
[[26483     0]
 [    0 47931]]
testing confusion matrix
[[ 6750     0]
 [    0 11854]]
------------------------------------------


In [20]:
an.navie_bayes_hash_model(route2_x.title,route2_y,100)

Splitting
Final size of train/test : 74414 / 18604
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7776090520600962
grid alpha 0.012
Alpha: 0.012 test_Score: 0.78693 train_score: 0.89194
training confusion matrix
[[19824  6659]
 [ 1382 46549]]
testing confusion matrix
[[ 3849  2901]
 [ 1063 10791]]
------------------------------------------


In [21]:
an.navie_bayes_hash_model(route2_x.authors,route2_y,100)

Splitting
Final size of train/test : 74414 / 18604
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9680436477007015
grid alpha 0.027000000000000003
Alpha: 0.027 test_Score: 0.96850 train_score: 0.97971
training confusion matrix
[[25288  1195]
 [  315 47616]]
testing confusion matrix
[[ 6312   438]
 [  148 11706]]
------------------------------------------


In [22]:
an.navie_bayes_hash_model(route2_x.content,route2_y,100)

Splitting
Final size of train/test : 74414 / 18604
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9333189991130701
grid alpha 0.002
Alpha: 0.002 test_Score: 0.93254 train_score: 0.96290
training confusion matrix
[[25006  1477]
 [ 1284 46647]]
testing confusion matrix
[[ 6010   740]
 [  515 11339]]
------------------------------------------


In [54]:
def mult_hash4(x1,x2,y,x3,x4,itera=100):
        from sklearn.feature_extraction.text import HashingVectorizer

        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        train_x4,train_y4,test_x4,test_y4=an.split_data(x3,y)

        
        hash_vectorizer = HashingVectorizer(stop_words='english',n_features=2**8)   # a HASH vectorizer
        
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()))  #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()) ) #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense()) )
        
        hash_train_x3 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x3).todense()))  #fitting the training data
        hash_test_x3 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x3).todense()))
        
        hash_train_x4 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x4).todense()) ) #fitting the training data
        hash_test_x4 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x4).todense()))
        
        train=pd.concat([hash_train_x1,hash_train_x2,hash_train_x3,hash_train_x4],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2,hash_test_x3,hash_test_x4],axis=1)
        
        an.navie_bayes(train,train_y2,test,test_y2,itera)


In [55]:
mult_hash4(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y,x4=route2_x.title)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9973123337006478
grid alpha 0.01
Alpha: 0.010 test_Score: 0.99699 train_score: 0.99734
training confusion matrix
[[26285   198]
 [    0 47931]]
testing confusion matrix
[[ 6694    56]
 [    0 11854]]
------------------------------------------


In [66]:
def multi_hashv(x1,x2,y,x3=a):
    from sklearn.feature_extraction.text import HashingVectorizer
  
    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**8)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()))  #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()))  #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense())) 

        train=pd.concat([hash_train_x1,hash_train_x2],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        an.navie_bayes(train,train_y2,test,test_y2,100)
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**8)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()) ) #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()) ) #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense()) )
        
        hash_train_x3 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x3).todense()))  #fitting the training data
        hash_test_x3 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x3).todense()))
        
        train=pd.concat([hash_train_x1,hash_train_x2,hash_train_x3],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2,hash_test_x3],axis=1)
        
        an.navie_bayes(train,train_y2,test,test_y2,100)


In [67]:
multi_hashv(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9962372671809068
grid alpha 0.01
Alpha: 0.010 test_Score: 0.99581 train_score: 0.99630
training confusion matrix
[[26208   275]
 [    0 47931]]
testing confusion matrix
[[ 6672    78]
 [    0 11854]]
------------------------------------------


In [ ]:
"""

unto pac tfidf

"""

In [76]:
ap.pac_tfidf_model(route2_x.domain,route2_y,False)

Final size of train/test : 74414 / 18604
train accuracy: 1.0
train confusion matrix
[[26483     0]
 [    0 47931]]
test accuracy: 1.0
test confusion matrix
[[ 6750     0]
 [    0 11854]]


In [77]:
ap.pac_tfidf_model(route2_x.content,route2_y,False)

Final size of train/test : 74414 / 18604
train accuracy: 0.9999865616685032
train confusion matrix
[[26483     0]
 [    1 47930]]
test accuracy: 0.9609761341646957
test confusion matrix
[[ 6365   385]
 [  341 11513]]


In [78]:
ap.pac_tfidf_model(route2_x.authors,route2_y,False)

Final size of train/test : 74414 / 18604
train accuracy: 0.9951487623296692
train confusion matrix
[[26233   250]
 [  111 47820]]
test accuracy: 0.9777467211352397
test confusion matrix
[[ 6540   210]
 [  204 11650]]


In [79]:
ap.pac_tfidf_model(route2_x.title,route2_y,False)

Final size of train/test : 74414 / 18604
train accuracy: 0.9573467358292794
train confusion matrix
[[24489  1994]
 [ 1180 46751]]
test accuracy: 0.7530101053536874
test confusion matrix
[[4188 2562]
 [2033 9821]]


In [80]:
ap.pac_tfidf_model(route2_x.domain,route2_y,True)

Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 1.0
train confusion matrix
[[26483     0]
 [    0 47931]]
test accuracy: 1.0
test confusion matrix
[[ 6750     0]
 [    0 11854]]


In [81]:
ap.pac_tfidf_model(route2_x.content,route2_y,True)

Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 0.9961431988604295
train confusion matrix
[[26358   125]
 [  162 47769]]
test accuracy: 0.9604923672328531
test confusion matrix
[[ 6385   365]
 [  370 11484]]


In [82]:
ap.pac_tfidf_model(route2_x.authors,route2_y,True)

Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 0.992568602682291
train confusion matrix
[[26138   345]
 [  208 47723]]
test accuracy: 0.9758654052891851
test confusion matrix
[[ 6513   237]
 [  212 11642]]


In [83]:
ap.pac_tfidf_model(route2_x.title,route2_y,True)

Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 0.9186443411186067
train confusion matrix
[[22696  3787]
 [ 2267 45664]]
test accuracy: 0.7723070307460761
test confusion matrix
[[ 4230  2520]
 [ 1716 10138]]


In [87]:
def mult_tfidf_pac(x1,x2,y,x3=a,stop=False):
    from sklearn.feature_extraction.text import TfidfVectorizer

    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 

        train=pd.concat([tfidf_train_x1,tfidf_train_x2],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        ap.passive_aggressive(train,train_y2,test,test_y2,stop)
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3],axis=1)
        
        ap.passive_aggressive(train,train_y2,test,test_y2,stop)

        

In [88]:
mult_tfidf_pac(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
train accuracy: 0.9940333808154379
train confusion matrix
[[26047   436]
 [    8 47923]]
test accuracy: 0.9855407439260374
test confusion matrix
[[ 6545   205]
 [   64 11790]]


In [89]:
mult_tfidf_pac(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y,stop=True)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 0.9959013088934878
train confusion matrix
[[26240   243]
 [   62 47869]]
test accuracy: 0.9878520748226188
test confusion matrix
[[ 6607   143]
 [   83 11771]]


In [91]:
def mult_tfidf4_pac(x1,x2,y,x3,x4,stop=False):
        from sklearn.feature_extraction.text import TfidfVectorizer

        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        train_x4,train_y4,test_x4,test_y4=an.split_data(x3,y)

        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7,min_df=0.02)   # a TFIDF vectorizer
        
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        tfidf_train_x4 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x4).todense())  #fitting the training data
        tfidf_test_x4 = pd.DataFrame(tfidf_vectorizer.transform(test_x4).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3,tfidf_train_x4],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3,tfidf_test_x4],axis=1)
        
        ap.passive_aggressive(train,train_y2,test,test_y2,stop)

In [92]:
mult_tfidf4_pac(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y,x4=route2_x.title)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
train accuracy: 0.9988039884967882
train confusion matrix
[[26472    11]
 [   78 47853]]
test accuracy: 0.9893571274994625
test confusion matrix
[[ 6680    70]
 [  128 11726]]


In [96]:
mult_tfidf4_pac(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y,x4=route2_x.title,stop=False)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
train accuracy: 0.9988443034912785
train confusion matrix
[[26455    28]
 [   58 47873]]
test accuracy: 0.9890346162115674
test confusion matrix
[[ 6664    86]
 [  118 11736]]


In [ ]:
#pac hash

In [97]:
ap.pac_hash_model(route2_x.domain,route2_y,False)

Final size of train/test : 74414 / 18604
train accuracy: 1.0
train confusion matrix
[[26483     0]
 [    0 47931]]
test accuracy: 1.0
test confusion matrix
[[ 6750     0]
 [    0 11854]]


In [98]:
ap.pac_hash_model(route2_x.content,route2_y,False)

Final size of train/test : 74414 / 18604
train accuracy: 0.999946246674013
train confusion matrix
[[26483     0]
 [    4 47927]]
test accuracy: 0.957052246828639
test confusion matrix
[[ 6352   398]
 [  401 11453]]


In [99]:
ap.pac_hash_model(route2_x.authors,route2_y,False)

Final size of train/test : 74414 / 18604
train accuracy: 0.9944365307603408
train confusion matrix
[[26187   296]
 [  118 47813]]
test accuracy: 0.9784992474736616
test confusion matrix
[[ 6527   223]
 [  177 11677]]


In [100]:
ap.pac_hash_model(route2_x.title,route2_y,False)

Final size of train/test : 74414 / 18604
train accuracy: 0.9501975434730023
train confusion matrix
[[24303  2180]
 [ 1526 46405]]
test accuracy: 0.759460331111589
test confusion matrix
[[4247 2503]
 [1972 9882]]


In [101]:
ap.pac_hash_model(route2_x.domain,route2_y,True)

Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 1.0
train confusion matrix
[[26483     0]
 [    0 47931]]
test accuracy: 1.0
test confusion matrix
[[ 6750     0]
 [    0 11854]]


In [102]:
ap.pac_hash_model(route2_x.content,route2_y,True)

Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 0.993576477544548
train confusion matrix
[[26190   293]
 [  185 47746]]
test accuracy: 0.9578047731670608
test confusion matrix
[[ 6310   440]
 [  345 11509]]


In [103]:
ap.pac_hash_model(route2_x.authors,route2_y,True)

Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 0.9917623027924853
train confusion matrix
[[26035   448]
 [  165 47766]]
test accuracy: 0.9783917437110299
test confusion matrix
[[ 6495   255]
 [  147 11707]]


In [104]:
ap.pac_hash_model(route2_x.title,route2_y,True)

Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 0.9026124116429705
train confusion matrix
[[22437  4046]
 [ 3201 44730]]
test accuracy: 0.7699419479681789
test confusion matrix
[[ 4310  2440]
 [ 1840 10014]]


In [105]:
def multi_hashv_pac(x1,x2,y,x3=a,stop=False):
    from sklearn.feature_extraction.text import HashingVectorizer
    # Not sure about this, collisions may occur as I forced absolute cause naivie bayes is a bitch and n_features over 
                                                                                        #2**15 causes memory error
    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**8)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()))  #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()))  #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense())) 

        train=pd.concat([hash_train_x1,hash_train_x2],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        ap.passive_aggressive(train,train_y2,test,test_y2,stop)    
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        hash_vectorizer = HashingVectorizer(stop_words='english',n_features = 2**8)   # a HASH vectorizer
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()) ) #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()) ) #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense()) )
        
        hash_train_x3 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x3).todense()))  #fitting the training data
        hash_test_x3 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x3).todense()))
        
        train=pd.concat([hash_train_x1,hash_train_x2,hash_train_x3],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2,hash_test_x3],axis=1)
        
        ap.passive_aggressive(train,train_y2,test,test_y2,stop)


In [107]:
multi_hashv_pac(x1=route2_x.content,x2=route2_x.authors,y=route2_y,x3=route2_x.domain,stop=False)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
train accuracy: 1.0
train confusion matrix
[[26483     0]
 [    0 47931]]
test accuracy: 1.0
test confusion matrix
[[ 6750     0]
 [    0 11854]]


In [108]:
multi_hashv_pac(x1=route2_x.content,x2=route2_x.authors,y=route2_y,x3=route2_x.domain,stop=True)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 1.0
train confusion matrix
[[26483     0]
 [    0 47931]]
test accuracy: 1.0
test confusion matrix
[[ 6750     0]
 [    0 11854]]


In [114]:
def mult_hash4_pac(x1,x2,y,x3,x4,stop=False):
        from sklearn.feature_extraction.text import HashingVectorizer

        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        train_x4,train_y4,test_x4,test_y4=an.split_data(x3,y)

        
        hash_vectorizer = HashingVectorizer(stop_words='english',n_features=2**8)   # a HASH vectorizer
        
        hash_train_x1 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x1).todense()))  #fitting the training data
        hash_test_x1 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x1).todense()))

        hash_train_x2 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x2).todense()) ) #fitting the training data
        hash_test_x2 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x2).todense()) )
        
        hash_train_x3 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x3).todense()))  #fitting the training data
        hash_test_x3 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x3).todense()))
        
        hash_train_x4 = pd.DataFrame(np.absolute(hash_vectorizer.fit_transform(train_x4).todense()) ) #fitting the training data
        hash_test_x4 = pd.DataFrame(np.absolute(hash_vectorizer.transform(test_x4).todense()))
        
        train=pd.concat([hash_train_x1,hash_train_x2,hash_train_x3,hash_train_x4],axis=1)
        test=pd.concat([hash_test_x1,hash_test_x2,hash_test_x3,hash_test_x4],axis=1)
        
        ap.passive_aggressive(train,train_y2,test,test_y2,stop)


In [115]:
mult_hash4_pac(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y,x4=route2_x.title,stop=False)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
train accuracy: 1.0
train confusion matrix
[[26483     0]
 [    0 47931]]
test accuracy: 1.0
test confusion matrix
[[ 6750     0]
 [    0 11854]]


In [116]:
mult_hash4_pac(x1=route2_x.domain,x2=route2_x.content,x3=route2_x.authors,y=route2_y,x4=route2_x.title,stop=True)

Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Splitting
Final size of train/test : 74414 / 18604
Early Stopping is being used
train accuracy: 1.0
train confusion matrix
[[26483     0]
 [    0 47931]]
test accuracy: 1.0
test confusion matrix
[[ 6750     0]
 [    0 11854]]
