In [1]:
import numpy as np
import import_ipynb
import auto_naive as an
import auto_pac as ap
import pandas as pd
#import dtale as d

importing Jupyter notebook from auto_naive.ipynb
importing Jupyter notebook from auto_pac.ipynb


In [2]:
data=pd.read_csv('ckg.csv')
#data1=d.show(data)
data.columns

Index(['text', 'ratingName', 'headline', 'keywords', 'source'], dtype='object')

In [3]:
data.dropna(inplace=True)

In [4]:
ap.pac_tfidf_model(data.text,data.ratingName)

Final size of train/test : 7468 / 1868
train accuracy: 0.9989287627209427
train confusion matrix
[[5486    1]
 [   7 1974]]
test accuracy: 0.7007494646680942
test confusion matrix
[[1130  285]
 [ 274  179]]


In [5]:
ap.pac_tfidf_model(data.text,data.ratingName,stop=True)

Final size of train/test : 7468 / 1868
Early Stopping is being used
train accuracy: 0.9617032672737011
train confusion matrix
[[5376  111]
 [ 175 1806]]
test accuracy: 0.7141327623126338
test confusion matrix
[[1162  253]
 [ 281  172]]


In [6]:
ap.pac_tfidf_model(data.headline,data.ratingName)

Final size of train/test : 7468 / 1868
train accuracy: 0.998393144081414
train confusion matrix
[[5486    1]
 [  11 1970]]
test accuracy: 0.7034261241970021
test confusion matrix
[[1137  278]
 [ 276  177]]


In [7]:
ap.pac_tfidf_model(data.headline,data.ratingName,stop=True)

Final size of train/test : 7468 / 1868
Early Stopping is being used
train accuracy: 0.9630423138725228
train confusion matrix
[[5375  112]
 [ 164 1817]]
test accuracy: 0.702355460385439
test confusion matrix
[[1136  279]
 [ 277  176]]


In [8]:
ap.pac_tfidf_model(data.keywords,data.ratingName)

Final size of train/test : 7468 / 1868
train accuracy: 0.763122656668452
train confusion matrix
[[4755  732]
 [1037  944]]
test accuracy: 0.6777301927194861
test confusion matrix
[[1138  277]
 [ 325  128]]


In [9]:
ap.pac_tfidf_model(data.keywords,data.ratingName,stop=True)

Final size of train/test : 7468 / 1868
Early Stopping is being used
train accuracy: 0.737814675950723
train confusion matrix
[[4367 1120]
 [ 838 1143]]
test accuracy: 0.6702355460385439
test confusion matrix
[[1058  357]
 [ 259  194]]


In [10]:
ap.pac_tfidf_model(data.source,data.ratingName)

Final size of train/test : 7468 / 1868
train accuracy: 0.7347348687734333
train confusion matrix
[[5487    0]
 [1981    0]]
test accuracy: 0.7574946466809421
test confusion matrix
[[1415    0]
 [ 453    0]]


In [11]:
ap.pac_tfidf_model(data.source,data.ratingName,stop=True)

Final size of train/test : 7468 / 1868
Early Stopping is being used
train accuracy: 0.56373861810391
train confusion matrix
[[3098 2389]
 [ 869 1112]]
test accuracy: 0.5802997858672377
test confusion matrix
[[824 591]
 [193 260]]


In [3]:
a=np.array([])
a.size

0

In [15]:
def mult_tfidf(x1,x2,x3,x4,y,stop=False):
    from sklearn.feature_extraction.text import TfidfVectorizer
    train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
    train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
    train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
    train_x4,train_y4,test_x4,test_y4=an.split_data(x4,y)
    
    tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorize
    
    tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
    tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

    tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
    tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
    tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
    tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
    tfidf_train_x4 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x4).todense())  #fitting the training data
    tfidf_test_x4 = pd.DataFrame(tfidf_vectorizer.transform(test_x4).todense())

    
    train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3,tfidf_train_x4],axis=1)
    test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3,tfidf_test_x4],axis=1)
        
    ap.passive_aggressive(train,train_y4,test,test_y4,stop)


In [16]:
mult_tfidf(data.text,data.headline,data.keywords,data.source,data.ratingName)

Splitting
Final size of train/test : 7468 / 1868
Splitting
Final size of train/test : 7468 / 1868
Splitting
Final size of train/test : 7468 / 1868
Splitting
Final size of train/test : 7468 / 1868
train accuracy: 0.9989287627209427
train confusion matrix
[[5481    6]
 [   2 1979]]
test accuracy: 0.7376873661670236
test confusion matrix
[[1193  222]
 [ 268  185]]


In [17]:
mult_tfidf(data.text,data.headline,data.keywords,data.source,data.ratingName,stop=True)

Splitting
Final size of train/test : 7468 / 1868
Splitting
Final size of train/test : 7468 / 1868
Splitting
Final size of train/test : 7468 / 1868
Splitting
Final size of train/test : 7468 / 1868
Early Stopping is being used
train accuracy: 0.9732190680235672
train confusion matrix
[[5398   89]
 [ 111 1870]]
test accuracy: 0.7355460385438972
test confusion matrix
[[1172  243]
 [ 251  202]]
