In [12]:
import numpy as np
import import_ipynb
import auto_naive as an
import auto_pac as ap
import pandas as pd


In [13]:
data=pd.read_csv('liar_data.csv')

data

label                                          statement  \
0         0  Says the Annies List political group supports ...   
1         0  When did the decline of coal start? It started...   
2         0  Hillary Clinton agrees with John McCain "by vo...   
3         0  The Chicago Bears have had more starting quart...   
4         0  I'm the only person on this stage who has work...   
...     ...                                                ...   
8433      1  Says U.S. Rep. Charles Bass wants to privatize...   
8434      0  In the past two years, Democrats have spent mo...   
8435      0  For the first time in more than a decade, impo...   
8436      0  Says Donald Trump has bankrupted his companies...   
8437      1  No one claims the report vindicating New Jerse...   

                                  subject            speaker  \
0                                abortion       dwayne-bohac   
1      energy,history,job-accomplishments     scott-surovell   
2                          foreign-policy       barack-obama   
3                               education          robin-vos   
4                                  ethics       barack-obama   
...                                   ...                ...   
8433                      social-security  ann-mclane-kuster   
8434               federal-budget,history        eric-cantor   
8435               energy,oil-spill,trade       barack-obama   
8436                 candidates-biography    hillary-clinton   
8437  candidates-biography,infrastructure      rudy-giuliani   

               speaker_job_title     state_info       party  \
0           State representative          Texas  republican   
1                 State delegate       Virginia    democrat   
2                      President       Illinois    democrat   
3     Wisconsin Assembly speaker      Wisconsin  republican   
4                      President       Illinois    democrat   
...                          ...            ...         ...   
8433                    Attorney  New Hampshire    democrat   
8434       House Majority Leader       Virginia  republican   
8435                   President       Illinois    democrat   
8436      Presidential candidate       New York    democrat   
8437                    Attorney       New York  republican   

                                                context  
0                                              a mailer  
1                                       a floor speech.  
2                                                Denver  
3                             a an online opinion-piece  
4              a Democratic debate in Philadelphia, Pa.  
...                                                 ...  
8433        an ad, “Janice,” released September 6, 2012  
8434  an interview on Comedy Central's Daily Show wi...  
8435                                 a press conference  
8436                            a speech on the economy  
8437                 comments on NBC's "Meet the Press"  

[8438 rows x 8 columns]

In [14]:
data.isna().sum()/(len(data))*100

label                0.0
statement            0.0
subject              0.0
speaker              0.0
speaker_job_title    0.0
state_info           0.0
party                0.0
context              0.0
dtype: float64

In [15]:
data

label                                          statement  \
0         0  Says the Annies List political group supports ...   
1         0  When did the decline of coal start? It started...   
2         0  Hillary Clinton agrees with John McCain "by vo...   
3         0  The Chicago Bears have had more starting quart...   
4         0  I'm the only person on this stage who has work...   
...     ...                                                ...   
8433      1  Says U.S. Rep. Charles Bass wants to privatize...   
8434      0  In the past two years, Democrats have spent mo...   
8435      0  For the first time in more than a decade, impo...   
8436      0  Says Donald Trump has bankrupted his companies...   
8437      1  No one claims the report vindicating New Jerse...   

                                  subject            speaker  \
0                                abortion       dwayne-bohac   
1      energy,history,job-accomplishments     scott-surovell   
2                          foreign-policy       barack-obama   
3                               education          robin-vos   
4                                  ethics       barack-obama   
...                                   ...                ...   
8433                      social-security  ann-mclane-kuster   
8434               federal-budget,history        eric-cantor   
8435               energy,oil-spill,trade       barack-obama   
8436                 candidates-biography    hillary-clinton   
8437  candidates-biography,infrastructure      rudy-giuliani   

               speaker_job_title     state_info       party  \
0           State representative          Texas  republican   
1                 State delegate       Virginia    democrat   
2                      President       Illinois    democrat   
3     Wisconsin Assembly speaker      Wisconsin  republican   
4                      President       Illinois    democrat   
...                          ...            ...         ...   
8433                    Attorney  New Hampshire    democrat   
8434       House Majority Leader       Virginia  republican   
8435                   President       Illinois    democrat   
8436      Presidential candidate       New York    democrat   
8437                    Attorney       New York  republican   

                                                context  
0                                              a mailer  
1                                       a floor speech.  
2                                                Denver  
3                             a an online opinion-piece  
4              a Democratic debate in Philadelphia, Pa.  
...                                                 ...  
8433        an ad, “Janice,” released September 6, 2012  
8434  an interview on Comedy Central's Daily Show wi...  
8435                                 a press conference  
8436                            a speech on the economy  
8437                 comments on NBC's "Meet the Press"  

[8438 rows x 8 columns]

In [16]:
#tfidf model building
an.navie_bayes_tfidf_model(data.statement,data.label)

Splitting
Final size of train/test : 6750 / 1688
train_x : (6750,)
train_y : (6750,)
test_x : (1688,)
test_y : (1688,)
Vectorizing
test_x : (1688,)
train_x : (6750,)
tfidf_train_x :  (6750, 9277)
tfidf_test_x :  (1688, 9277)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7401481481481481
grid alpha 0.9480000000000001
Alpha: 0.948 test_Score: 0.71979 train_score: 0.75674
training confusion matrix
[[4994    0]
 [1642  114]]
testing confusion matrix
[[1214    3]
 [ 470    1]]
------------------------------------------


In [17]:

an.navie_bayes_tfidf_model(data.subject,data.label)

Splitting
Final size of train/test : 6750 / 1688
train_x : (6750,)
train_y : (6750,)
test_x : (1688,)
test_y : (1688,)
Vectorizing
test_x : (1688,)
train_x : (6750,)
tfidf_train_x :  (6750, 174)
tfidf_test_x :  (1688, 174)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.737037037037037
grid alpha 0.5710000000000001
Alpha: 0.571 test_Score: 0.72097 train_score: 0.74000
training confusion matrix
[[4993    1]
 [1754    2]]
testing confusion matrix
[[1217    0]
 [ 471    0]]
------------------------------------------


In [18]:
an.navie_bayes_tfidf_model(data.speaker,data.label)

Splitting
Final size of train/test : 6750 / 1688
train_x : (6750,)
train_y : (6750,)
test_x : (1688,)
test_y : (1688,)
Vectorizing
test_x : (1688,)
train_x : (6750,)
tfidf_train_x :  (6750, 2049)
tfidf_test_x :  (1688, 2049)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7282962962962963
grid alpha 0.999
Alpha: 0.999 test_Score: 0.71505 train_score: 0.77052
training confusion matrix
[[4964   30]
 [1519  237]]
testing confusion matrix
[[1188   29]
 [ 452   19]]
------------------------------------------


In [29]:
an.navie_bayes_tfidf_model(data.speaker_job_title,data.label)

Splitting
Final size of train/test : 6750 / 1688
train_x : (6750,)
train_y : (6750,)
test_x : (1688,)
test_y : (1688,)
Vectorizing
test_x : (1688,)
train_x : (6750,)
tfidf_train_x :  (6750, 979)
tfidf_test_x :  (1688, 979)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7294814814814815
grid alpha 0.9520000000000001
Alpha: 0.952 test_Score: 0.71445 train_score: 0.75156
training confusion matrix
[[4966   28]
 [1649  107]]
testing confusion matrix
[[1199   18]
 [ 464    7]]
------------------------------------------


In [19]:
an.navie_bayes_tfidf_model(data.state_info,data.label)

Splitting
Final size of train/test : 6750 / 1688
train_x : (6750,)
train_y : (6750,)
test_x : (1688,)
test_y : (1688,)
Vectorizing
test_x : (1688,)
train_x : (6750,)
tfidf_train_x :  (6750, 69)
tfidf_test_x :  (1688, 69)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7386666666666667
grid alpha 0.021
Alpha: 0.021 test_Score: 0.72097 train_score: 0.74059
training confusion matrix
[[4993    1]
 [1750    6]]
testing confusion matrix
[[1217    0]
 [ 471    0]]
------------------------------------------


In [9]:
an.navie_bayes_tfidf_model(data.party,data.label)

Splitting
Final size of train/test : 10232 / 2559
train_x : (10232,)
train_y : (10232,)
test_x : (2559,)
test_y : (2559,)
Vectorizing
test_x : (2559,)
train_x : (10232,)
tfidf_train_x :  (10232, 34)
tfidf_test_x :  (2559, 34)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7359265050820953
grid alpha 0.441
Alpha: 0.441 test_Score: 0.72567 train_score: 0.73632
training confusion matrix
[[7532    1]
 [2697    2]]
testing confusion matrix
[[1857    0]
 [ 702    0]]
------------------------------------------


In [21]:
an.navie_bayes_tfidf_model(data.context,data.label)

Splitting
Final size of train/test : 6750 / 1688
train_x : (6750,)
train_y : (6750,)
test_x : (1688,)
test_y : (1688,)
Vectorizing
test_x : (1688,)
train_x : (6750,)
tfidf_train_x :  (6750, 1691)
tfidf_test_x :  (1688, 1691)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7300740740740741
grid alpha 0.987
Alpha: 0.987 test_Score: 0.71209 train_score: 0.75896
training confusion matrix
[[4971   23]
 [1604  152]]
testing confusion matrix
[[1197   20]
 [ 466    5]]
------------------------------------------


In [22]:
#hashing model
an.navie_bayes_hash_model(data.statement,data.label)


Splitting
Final size of train/test : 6750 / 1688
Vectorizing
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7401481481481481
grid alpha 0.075
Alpha: 0.075 test_Score: 0.72156 train_score: 0.74667
training confusion matrix
[[4994    0]
 [1710   46]]
testing confusion matrix
[[1217    0]
 [ 470    1]]
------------------------------------------


In [23]:
an.navie_bayes_hash_model(data.subject,data.label)

Splitting
Final size of train/test : 6750 / 1688
Vectorizing
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7398518518518519
grid alpha 0.004
Alpha: 0.004 test_Score: 0.72097 train_score: 0.74000
training confusion matrix
[[4994    0]
 [1755    1]]
testing confusion matrix
[[1217    0]
 [ 471    0]]
------------------------------------------


In [24]:
an.navie_bayes_hash_model(data.speaker,data.label)

Splitting
Final size of train/test : 6750 / 1688
Vectorizing
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7388148148148148
grid alpha 0.844
Alpha: 0.844 test_Score: 0.71860 train_score: 0.74252
training confusion matrix
[[4994    0]
 [1738   18]]
testing confusion matrix
[[1213    4]
 [ 471    0]]
------------------------------------------


In [25]:
an.navie_bayes_hash_model(data.speaker_job_title,data.label)

Splitting
Final size of train/test : 6750 / 1688
Vectorizing
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7388148148148148
grid alpha 0.652
Alpha: 0.652 test_Score: 0.72097 train_score: 0.74044
training confusion matrix
[[4994    0]
 [1752    4]]
testing confusion matrix
[[1217    0]
 [ 471    0]]
------------------------------------------


In [26]:
an.navie_bayes_hash_model(data.state_info,data.label)

Splitting
Final size of train/test : 6750 / 1688
Vectorizing
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7397037037037038
grid alpha 0.547
Alpha: 0.547 test_Score: 0.72097 train_score: 0.74030
training confusion matrix
[[4994    0]
 [1753    3]]
testing confusion matrix
[[1217    0]
 [ 471    0]]
------------------------------------------


In [27]:
an.navie_bayes_hash_model(data.party,data.label)

Splitting
Final size of train/test : 6750 / 1688
Vectorizing
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7398518518518519
grid alpha 0.003
Alpha: 0.003 test_Score: 0.72097 train_score: 0.74000
training confusion matrix
[[4994    0]
 [1755    1]]
testing confusion matrix
[[1217    0]
 [ 471    0]]
------------------------------------------


In [30]:
an.navie_bayes_hash_model(data.context,data.label)

Splitting
Final size of train/test : 6750 / 1688
Vectorizing
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7398518518518519
grid alpha 0.773
Alpha: 0.773 test_Score: 0.72097 train_score: 0.73985
training confusion matrix
[[4994    0]
 [1756    0]]
testing confusion matrix
[[1217    0]
 [ 471    0]]
------------------------------------------


In [32]:
a=np.array([])
a.size

0

In [33]:
def mult_tfidf(x1,x2,y,x3=a):
    from sklearn.feature_extraction.text import TfidfVectorizer

    if x3.size==0:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)



        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 

        train=pd.concat([tfidf_train_x1,tfidf_train_x2],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2],axis=1)
        print(train.shape)
        print(test.shape)
        print(train_y2.shape)
        print(test_y2.shape)

        an.navie_bayes(train,train_y2,test,test_y2)
    
    else:
        train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
        train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
        train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
        
        tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorizer
        tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
        tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

        tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
        tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
        tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
        tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
        train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3],axis=1)
        test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3],axis=1)
        
        an.navie_bayes(train,train_y2,test,test_y2)


In [34]:
data.columns

Index(['label', 'statement', 'subject', 'speaker', 'speaker_job_title',
       'state_info', 'party', 'context'],
      dtype='object')

In [35]:
#navie bayes tfdif model with 2 attribute
mult_tfidf(data.statement,data.subject,data.label)


Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
(6750, 9451)
(1688, 9451)
(6750,)
(1688,)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7394074074074074
grid alpha 0.921
Alpha: 0.921 test_Score: 0.72216 train_score: 0.75274
training confusion matrix
[[4993    1]
 [1668   88]]
testing confusion matrix
[[1216    1]
 [ 468    3]]
------------------------------------------


In [36]:
mult_tfidf(data.statement,data.state_info,data.label)

Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
(6750, 9346)
(1688, 9346)
(6750,)
(1688,)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7397037037037038
grid alpha 0.844
Alpha: 0.844 test_Score: 0.72156 train_score: 0.75659
training confusion matrix
[[4992    2]
 [1641  115]]
testing confusion matrix
[[1217    0]
 [ 470    1]]
------------------------------------------


In [37]:
mult_tfidf(data.statement,data.party,data.label)

Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
(6750, 9305)
(1688, 9305)
(6750,)
(1688,)
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.7395555555555555
grid alpha 0.966
Alpha: 0.966 test_Score: 0.72097 train_score: 0.74933
training confusion matrix
[[4993    1]
 [1691   65]]
testing confusion matrix
[[1216    1]
 [ 470    1]]
------------------------------------------


In [39]:
def mult_tfidf(x1,x2,x3,x4,x5,x6,x7,y):
    from sklearn.feature_extraction.text import TfidfVectorizer
    train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
    train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
    train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
    train_x4,train_y4,test_x4,test_y4=an.split_data(x5,y)
    train_x5,train_y5,test_x5,test_y5=an.split_data(x5,y)
    train_x6,train_y6,test_x6,test_y6=an.split_data(x6,y)
    train_x7,train_y7,test_x7,test_y7=an.split_data(x7,y)
    
    tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorize
    
    tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
    tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

    tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
    tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
    tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
    tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
    tfidf_train_x4 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x4).todense())  #fitting the training data
    tfidf_test_x4 = pd.DataFrame(tfidf_vectorizer.transform(test_x4).todense())

    tfidf_train_x5 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x5).todense())  #fitting the training data
    tfidf_test_x5 = pd.DataFrame(tfidf_vectorizer.transform(test_x5).todense()) 
        
    tfidf_train_x6 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x6).todense())  #fitting the training data
    tfidf_test_x6 = pd.DataFrame(tfidf_vectorizer.transform(test_x6).todense())
    
    tfidf_train_x7 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x7).todense())  #fitting the training data
    tfidf_test_x7 = pd.DataFrame(tfidf_vectorizer.transform(test_x7).todense())
        
    train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3,tfidf_train_x4,tfidf_train_x5,tfidf_train_x6,tfidf_train_x7],axis=1)
    test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3,tfidf_test_x4,tfidf_test_x5,tfidf_test_x6,tfidf_test_x7],axis=1)
        
    an.navie_bayes(train,train_y7,test,test_y7)


In [40]:
#navie bayes tfdif model with all attribute
mult_tfidf(data.statement,data.subject,data.speaker,data.speaker_job_title,data.state_info,data.party,data.context,data.label)

Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
Splitting
Final size of train/test : 6750 / 1688
model building
begin grid


C:\Users\shiva\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.737037037037037
grid alpha 0.993
Alpha: 0.993 test_Score: 0.71860 train_score: 0.77437
training confusion matrix
[[4978   16]
 [1507  249]]
testing confusion matrix
[[1206   11]
 [ 464    7]]
------------------------------------------
