In [1]:
import pandas as pd
import numpy as np
import import_ipynb
import auto_naive as an
import auto_pac as ap

importing Jupyter notebook from auto_naive.ipynb
importing Jupyter notebook from auto_pac.ipynb


In [2]:
superset=pd.read_csv('datasets/superset.csv')

In [3]:
superset

label                                          statement
0       fake  About 47 percent of able-bodied people in the ...
1       true  Says Dan Patrick has "called immigration into ...
2       true  In 2008, "only 54 percent of Latinos in Texas ...
3       true  Even after Obamacare is fully implemented, the...
4       true  McDonald's in England only sells organic milk ...
...      ...                                                ...
233408  fake  There are a larger number of shark attacks in ...
233409  fake  Democrats have now become the party of the [At...
233410  fake  Says an alternative to Social Security that op...
233411  fake  On lifting the U.S. Cuban embargo and allowing...
233412  fake  The Department of Veterans Affairs has a manua...

[233413 rows x 2 columns]

In [4]:
super_x=superset.statement
super_y=superset.label

In [5]:
print(super_x.shape)
print(super_y.shape)

(233413,)
(233413,)


In [6]:
import time 


In [7]:
start=time.time()
an.navie_bayes_tfidf_model(super_x,super_y,100)
stop=time.time()
print((stop-start)/60)

Splitting
Final size of train/test : 186730 / 46683
train_x : (186730,)
train_y : (186730,)
test_x : (46683,)
test_y : (46683,)
Vectorizing
test_x : (46683,)
train_x : (186730,)
tfidf_train_x :  (186730, 473389)
tfidf_test_x :  (46683, 473389)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.8443635195201628
grid alpha 0.030000000000000002
Alpha: 0.030 test_Score: 0.84626 train_score: 0.88718
training confusion matrix
[[67585 10977]
 [10089 98079]]
testing confusion matrix
[[15544  4017]
 [ 3160 23962]]
------------------------------------------
41.32438203493754


In [8]:
start=time.time()
ap.pac_tfidf_model(super_x,super_y,stop=False)
stop=time.time()
print((stop-start)/60)

Final size of train/test : 186730 / 46683
train accuracy: 0.9709687784501687
train confusion matrix
[[ 76207   2355]
 [  3066 105102]]
test accuracy: 0.8553434869224343
test confusion matrix
[[16208  3353]
 [ 3400 23722]]
1.2414656440416971


In [9]:
start=time.time()
ap.pac_tfidf_model(super_x,super_y,stop=True)
stop=time.time()
print((stop-start)/60)

Final size of train/test : 186730 / 46683
Early Stopping is being used
train accuracy: 0.9432335457612596
train confusion matrix
[[ 74768   3794]
 [  6806 101362]]
test accuracy: 0.8710665552770815
test confusion matrix
[[17028  2533]
 [ 3486 23636]]
1.1519471724828085
