In [1]:
import numpy as np
import import_ipynb
import auto_naive as an
import auto_pac as ap
import pandas as pd
import dtale as d

importing Jupyter notebook from auto_naive.ipynb
importing Jupyter notebook from auto_pac.ipynb


In [2]:
data=pd.read_csv('ckg.csv')
data1=d.show(data)
data.columns

Index(['text', 'ratingName', 'headline', 'keywords', 'source'], dtype='object')

In [3]:
data.dropna(inplace=True)

In [11]:
an.navie_bayes_tfidf_model(data.text,data.ratingName)

Splitting
Final size of train/test : 7468 / 1868
train_x : (7468,)
train_y : (7468,)
test_x : (1868,)
test_y : (1868,)
Vectorizing
test_x : (1868,)
train_x : (7468,)
tfidf_train_x :  (7468, 13975)
tfidf_test_x :  (1868, 13975)
model building
begin grid


C:\Users\3 idiots\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning:

The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.



grid score 0.7379485806106052
grid alpha 0.47600000000000003
Alpha: 0.476 test_Score: 0.76552 train_score: 0.84788
training confusion matrix
[[5476   11]
 [1125  856]]
testing confusion matrix
[[1394   21]
 [ 417   36]]
------------------------------------------


In [12]:
an.navie_bayes_tfidf_model(data.headline,data.ratingName)

Splitting
Final size of train/test : 7468 / 1868
train_x : (7468,)
train_y : (7468,)
test_x : (1868,)
test_y : (1868,)
Vectorizing
test_x : (1868,)
train_x : (7468,)
tfidf_train_x :  (7468, 11242)
tfidf_test_x :  (1868, 11242)
model building
begin grid


C:\Users\3 idiots\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning:

The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.



grid score 0.7430369576861274
grid alpha 0.552
Alpha: 0.552 test_Score: 0.77355 train_score: 0.86476
training confusion matrix
[[5482    5]
 [1005  976]]
testing confusion matrix
[[1392   23]
 [ 400   53]]
------------------------------------------


In [14]:
an.navie_bayes_tfidf_model(data.source,data.ratingName)

Splitting
Final size of train/test : 7468 / 1868
train_x : (7468,)
train_y : (7468,)
test_x : (1868,)
test_y : (1868,)
Vectorizing
test_x : (1868,)
train_x : (7468,)
tfidf_train_x :  (7468, 4)
tfidf_test_x :  (1868, 4)
model building
begin grid


C:\Users\3 idiots\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning:

The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.



grid score 0.7347348687734333
grid alpha 0.001
Alpha: 0.001 test_Score: 0.75428 train_score: 0.73514
training confusion matrix
[[5470   17]
 [1961   20]]
testing confusion matrix
[[1406    9]
 [ 450    3]]
------------------------------------------


In [4]:
an.navie_bayes_tfidf_model(data.keywords,data.ratingName)

Splitting
Final size of train/test : 7468 / 1868
train_x : (7468,)
train_y : (7468,)
test_x : (1868,)
test_y : (1868,)
Vectorizing
test_x : (1868,)
train_x : (7468,)
tfidf_train_x :  (7468, 3910)
tfidf_test_x :  (1868, 3910)
model building
begin grid


C:\Users\3 idiots\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning:

The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.



grid score 0.7333958221746116
grid alpha 0.988
Alpha: 0.988 test_Score: 0.74946 train_score: 0.76701
training confusion matrix
[[5445   42]
 [1698  283]]
testing confusion matrix
[[1380   35]
 [ 433   20]]
------------------------------------------
Exception occurred while processing request: '2'
Traceback (most recent call last):
  File "C:\Users\3 idiots\Anaconda3\lib\site-packages\dtale\views.py", line 935, in get_data
    data = DATA[data_id]
KeyError: '2'


2020-02-26 20:08:22,794 - ERROR    - Exception occurred while processing request: '2'
Traceback (most recent call last):
  File "C:\Users\3 idiots\Anaconda3\lib\site-packages\dtale\views.py", line 935, in get_data
    data = DATA[data_id]
KeyError: '2'


In [5]:
def mult_tfidf(x1,x2,x3,x4,y):
    from sklearn.feature_extraction.text import TfidfVectorizer
    train_x1,train_y1,test_x1,test_y1=an.split_data(x1,y)
    train_x2,train_y2,test_x2,test_y2=an.split_data(x2,y)
    train_x3,train_y3,test_x3,test_y3=an.split_data(x3,y)
    train_x4,train_y4,test_x4,test_y4=an.split_data(x4,y)
    
    tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)   # a TFIDF vectorize
    
    tfidf_train_x1 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x1).todense())  #fitting the training data
    tfidf_test_x1 = pd.DataFrame(tfidf_vectorizer.transform(test_x1).todense())

    tfidf_train_x2 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x2).todense())  #fitting the training data
    tfidf_test_x2 = pd.DataFrame(tfidf_vectorizer.transform(test_x2).todense()) 
        
    tfidf_train_x3 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x3).todense())  #fitting the training data
    tfidf_test_x3 = pd.DataFrame(tfidf_vectorizer.transform(test_x3).todense())
        
    tfidf_train_x4 = pd.DataFrame(tfidf_vectorizer.fit_transform(train_x4).todense())  #fitting the training data
    tfidf_test_x4 = pd.DataFrame(tfidf_vectorizer.transform(test_x4).todense())

    
    train=pd.concat([tfidf_train_x1,tfidf_train_x2,tfidf_train_x3,tfidf_train_x4],axis=1)
    test=pd.concat([tfidf_test_x1,tfidf_test_x2,tfidf_test_x3,tfidf_test_x4],axis=1)
        
    an.navie_bayes(train,train_y4,test,test_y4)


In [6]:
data.columns

Index(['text', 'ratingName', 'headline', 'keywords', 'source'], dtype='object')

In [7]:
mult_tfidf(data.text,data.headline,data.keywords,data.source,data.ratingName)

Splitting
Final size of train/test : 7468 / 1868
Splitting
Final size of train/test : 7468 / 1868
Splitting
Final size of train/test : 7468 / 1868
Splitting
Final size of train/test : 7468 / 1868
model building
begin grid


C:\Users\3 idiots\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning:

The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.



Executing shutdown due to inactivity...


2020-02-26 14:51:45,908 - INFO     - Executing shutdown due to inactivity...


Executing shutdown...


2020-02-26 14:51:48,366 - INFO     - Executing shutdown...


grid score 0.7521424745581147
grid alpha 0.6900000000000001
Alpha: 0.690 test_Score: 0.77248 train_score: 0.89448
training confusion matrix
[[5404   83]
 [ 705 1276]]
testing confusion matrix
[[1352   63]
 [ 362   91]]
------------------------------------------
