In [1]:
"""
TODO - Naive Bayes and pac on newsfiles datasets

"""

'\nTODO - Naive Bayes and pac on newsfiles datasets\n\n'

In [2]:
import pandas as pd
import numpy as np
import import_ipynb
import auto_naive as an
import auto_pac as ap

importing Jupyter notebook from auto_naive.ipynb
importing Jupyter notebook from auto_pac.ipynb


In [3]:
news_train=pd.read_csv('datasets/newsfiles/fulltrain.csv',names=['label','Statement'])
news_test=pd.read_csv('datasets/newsfiles/newsfiles_test.csv',names=['label','Statement'])

In [4]:
print(news_train.shape)
print(news_test.shape)

(48854, 2)
(3000, 2)


In [5]:
#Ratings are as follows 1:"Satire",2:"Hoax",3:"Propaganda",4:"Trusted"
#Change Hoax to False(0) and Trusted to True(1) and remove Satire and Propaganda

def nf_ratechange(x):
    h=0
    for i in x.label:
        if i==2:
            x.at[h,'label']= 0
            
        elif i==4:
            x.at[h,'label']= 1
            
        elif i==1 or i==3:
            x.drop([h],inplace=True)
        h=h+1

In [6]:
nf_ratechange(news_train)

In [7]:
nf_ratechange(news_test)

In [8]:
print(news_train.shape)
print(news_test.shape)

(16937, 2)
(1500, 2)


In [9]:
news=pd.concat([news_train,news_test])

In [10]:
news.shape

(18437, 2)

In [11]:
news_x=news.Statement
news_y=news.label

In [12]:
print(news_x.shape,news_y.shape)

(18437,) (18437,)


In [13]:
an.navie_bayes_tfidf_model(news_x,news_y)

Splitting
Final size of train/test : 14749 / 3688
train_x : (14749,)
train_y : (14749,)
test_x : (3688,)
test_y : (3688,)
Vectorizing
test_x : (3688,)
train_x : (14749,)
tfidf_train_x :  (14749, 87642)
tfidf_test_x :  (3688, 87642)
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9747779510475286
grid alpha 0.005
Alpha: 0.005 test_Score: 0.97804 train_score: 0.99654
training confusion matrix
[[6095   14]
 [  37 8603]]
testing confusion matrix
[[1527   56]
 [  25 2080]]
------------------------------------------


In [14]:
an.navie_bayes_hash_model(news_x,news_y)

Splitting
Final size of train/test : 14749 / 3688
Vectorizing
model building
begin grid


C:\Users\Rahul\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


grid score 0.9791172282866635
grid alpha 0.002
Alpha: 0.002 test_Score: 0.98238 train_score: 0.99505
training confusion matrix
[[6068   41]
 [  32 8608]]
testing confusion matrix
[[1531   52]
 [  13 2092]]
------------------------------------------


In [15]:
ap.pac_tfidf_model(news_x,news_y,stop=False)

Final size of train/test : 14749 / 3688
train accuracy: 1.0
train confusion matrix
[[6109    0]
 [   0 8640]]
test accuracy: 0.9902386117136659
test confusion matrix
[[1557   26]
 [  10 2095]]


In [16]:
ap.pac_hash_model(news_x,news_y,stop=False)

Final size of train/test : 14749 / 3688
train accuracy: 1.0
train confusion matrix
[[6109    0]
 [   0 8640]]
test accuracy: 0.9886117136659436
test confusion matrix
[[1557   26]
 [  16 2089]]


In [17]:
ap.pac_tfidf_model(news_x,news_y,stop=True)

Final size of train/test : 14749 / 3688
Early Stopping is being used
train accuracy: 0.9989151806902162
train confusion matrix
[[6102    7]
 [   9 8631]]
test accuracy: 0.9902386117136659
test confusion matrix
[[1557   26]
 [  10 2095]]


In [18]:
ap.pac_hash_model(news_x,news_y,stop=True)

Final size of train/test : 14749 / 3688
Early Stopping is being used
train accuracy: 0.9987795782764933
train confusion matrix
[[6099   10]
 [   8 8632]]
test accuracy: 0.988882863340564
test confusion matrix
[[1557   26]
 [  15 2090]]
